/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteSelfBeneficiariesTPTBeneficiaryIdResponse;
import io.swagger.client.model.GetSelfBeneficiariesTPTResponse;
import io.swagger.client.model.GetSelfBeneficiariesTPTTemplateResponse;
import io.swagger.client.model.PostSelfBeneficiariesTPTRequest;
import io.swagger.client.model.PostSelfBeneficiariesTPTResponse;
import io.swagger.client.model.PutSelfBeneficiariesTPTBeneficiaryIdRequest;
import io.swagger.client.model.PutSelfBeneficiariesTPTBeneficiaryIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BeneficiaryThirdPartyTransferApi
 */
@Ignore
public class BeneficiaryThirdPartyTransferApiTest {

    private final BeneficiaryThirdPartyTransferApi api = new BeneficiaryThirdPartyTransferApi();

    
    /**
     * Add TPT Beneficiary
     *
     * Api to add third party beneficiary linked to current user.  Parameter Definitions  name : Nick name for beneficiary, should be unique for an self service user  officeName : Office Name of beneficiary(not id)  accountNumber : Account Number of beneficiary(not id)  transferLimit : Each transfer initiated to this account will not exceed this amount  Example Requests:  /self/beneficiaries/tpt  Mandatory Fields: name, officeName, accountNumber, accountType  Optional Fields: transferLimit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        PostSelfBeneficiariesTPTRequest body = null;
        PostSelfBeneficiariesTPTResponse response = api.add(body);

        // TODO: test validations
    }
    
    /**
     * Delete TPT Beneficiary
     *
     * Api to delete third party beneficiary linked to current user.  Example Requests:  /self/beneficiaries/tpt/{beneficiaryId}
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        Long beneficiaryId = null;
        DeleteSelfBeneficiariesTPTBeneficiaryIdResponse response = api.delete(beneficiaryId);

        // TODO: test validations
    }
    
    /**
     * Get All TPT Beneficiary
     *
     * Api to get all third party beneficiary linked to current user.  Example Requests:  /self/beneficiaries/tpt
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAllTest() throws ApiException {
        List<GetSelfBeneficiariesTPTResponse> response = api.retrieveAll();

        // TODO: test validations
    }
    
    /**
     * Beneficiary Third Party Transfer Template
     *
     * Returns Account Type enumerations. Self User is expected to know office name and account number to be able to add beneficiary.  Example Requests:  /self/beneficiaries/tpt/template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void templateTest() throws ApiException {
        GetSelfBeneficiariesTPTTemplateResponse response = api.template();

        // TODO: test validations
    }
    
    /**
     * Update TPT Beneficiary
     *
     * Api to update third party beneficiary linked to current user.  Example Requests:  /self/beneficiaries/tpt/{beneficiaryId}  Optional Fields: name, transferLimit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        Long beneficiaryId = null;
        PutSelfBeneficiariesTPTBeneficiaryIdRequest body = null;
        PutSelfBeneficiariesTPTBeneficiaryIdResponse response = api.update(beneficiaryId, body);

        // TODO: test validations
    }
    
}
