/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteClientsClientIdIdentifiersIdentifierIdResponse;
import io.swagger.client.model.GetClientsClientIdIdentifiersResponse;
import io.swagger.client.model.GetClientsClientIdIdentifiersTemplateResponse;
import io.swagger.client.model.PostClientsClientIdIdentifiersRequest;
import io.swagger.client.model.PostClientsClientIdIdentifiersResponse;
import io.swagger.client.model.PutClientsClientIdIdentifiersIdentifierIdRequest;
import io.swagger.client.model.PutClientsClientIdIdentifiersIdentifierIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientIdentifierApi
 */
@Ignore
public class ClientIdentifierApiTest {

    private final ClientIdentifierApi api = new ClientIdentifierApi();

    
    /**
     * Create an Identifier for a Client
     *
     * Mandatory Fields documentKey, documentTypeId 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createClientIdentifierTest() throws ApiException {
        Long clientId = null;
        PostClientsClientIdIdentifiersRequest body = null;
        PostClientsClientIdIdentifiersResponse response = api.createClientIdentifier(clientId, body);

        // TODO: test validations
    }
    
    /**
     * Delete a Client Identifier
     *
     * Deletes a Client Identifier
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClientIdentifierTest() throws ApiException {
        Long clientId = null;
        Long identifierId = null;
        DeleteClientsClientIdIdentifiersIdentifierIdResponse response = api.deleteClientIdentifier(clientId, identifierId);

        // TODO: test validations
    }
    
    /**
     * Retrieve Client Identifier Details Template
     *
     * This is a convenience resource useful for building maintenance user interface screens for client applications. The template data returned consists of any or all of:   Field Defaults  Allowed Value Lists   Example Request: clients/1/identifiers/template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newClientIdentifierDetailsTest() throws ApiException {
        GetClientsClientIdIdentifiersTemplateResponse response = api.newClientIdentifierDetails();

        // TODO: test validations
    }
    
    /**
     * List all Identifiers for a Client
     *
     * Example Requests: clients/1/identifiers   clients/1/identifiers?fields&#x3D;documentKey,documentType,description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAllClientIdentifiersTest() throws ApiException {
        Long clientId = null;
        List<GetClientsClientIdIdentifiersResponse> response = api.retrieveAllClientIdentifiers(clientId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a Client Identifier
     *
     * Example Requests: clients/1/identifier/2   clients/1/identifier/2?template&#x3D;true  clients/1/identifiers/2?fields&#x3D;documentKey,documentType,description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveClientIdentifiersTest() throws ApiException {
        Long clientId = null;
        Long identifierId = null;
        GetClientsClientIdIdentifiersResponse response = api.retrieveClientIdentifiers(clientId, identifierId);

        // TODO: test validations
    }
    
    /**
     * Update a Client Identifier
     *
     * Updates a Client Identifier
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClientIdentiferTest() throws ApiException {
        Long clientId = null;
        Long identifierId = null;
        PutClientsClientIdIdentifiersIdentifierIdRequest body = null;
        PutClientsClientIdIdentifiersIdentifierIdResponse response = api.updateClientIdentifer(clientId, identifierId, body);

        // TODO: test validations
    }
    
}
