/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteLoansLoanIdResponse;
import java.io.File;
import io.swagger.client.model.GetLoansLoanIdResponse;
import io.swagger.client.model.GetLoansResponse;
import io.swagger.client.model.GetLoansTemplateResponse;
import io.swagger.client.model.PostLoansLoanIdRequest;
import io.swagger.client.model.PostLoansLoanIdResponse;
import io.swagger.client.model.PostLoansRequest;
import io.swagger.client.model.PostLoansResponse;
import io.swagger.client.model.PutLoansLoanIdRequest;
import io.swagger.client.model.PutLoansLoanIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LoansApi
 */
@Ignore
public class LoansApiTest {

    private final LoansApi api = new LoansApi();

    
    /**
     * Calculate loan repayment schedule | Submit a new Loan Application
     *
     * It calculates the loan repayment Schedule Submits a new loan application Mandatory Fields: clientId, productId, principal, loanTermFrequency, loanTermFrequencyType, loanType, numberOfRepayments, repaymentEvery, repaymentFrequencyType, interestRatePerPeriod, amortizationType, interestType, interestCalculationPeriodType, transactionProcessingStrategyId, expectedDisbursementDate, submittedOnDate, loanType Optional Fields: graceOnPrincipalPayment, graceOnInterestPayment, graceOnInterestCharged, linkAccountId, allowPartialPeriodInterestCalcualtion, fixedEmiAmount, maxOutstandingLoanBalance, disbursementData, graceOnArrearsAgeing, createStandingInstructionAtDisbursement (requires linkedAccountId if set to true) Additional Mandatory Fields if interest recalculation is enabled for product and Rest frequency not same as repayment period: recalculationRestFrequencyDate Additional Mandatory Fields if interest recalculation with interest/fee compounding is enabled for product and compounding frequency not same as repayment period: recalculationCompoundingFrequencyDate Additional Mandatory Field if Entity-Datatable Check is enabled for the entity of type loan: datatables
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calculateLoanScheduleOrSubmitLoanApplicationTest() throws ApiException {
        PostLoansRequest body = null;
        String command = null;
        PostLoansResponse response = api.calculateLoanScheduleOrSubmitLoanApplication(body, command);

        // TODO: test validations
    }
    
    /**
     * Delete a Loan Application
     *
     * Note: Only loans in \&quot;Submitted and awaiting approval\&quot; status can be deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteLoanApplicationTest() throws ApiException {
        Long loanId = null;
        DeleteLoansLoanIdResponse response = api.deleteLoanApplication(loanId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoanRepaymentTemplateTest() throws ApiException {
        Long officeId = null;
        String dateFormat = null;
        api.getLoanRepaymentTemplate(officeId, dateFormat);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoansTemplateTest() throws ApiException {
        Long officeId = null;
        Long staffId = null;
        String dateFormat = null;
        api.getLoansTemplate(officeId, staffId, dateFormat);

        // TODO: test validations
    }
    
    /**
     * Modify a loan application
     *
     * Loan application can only be modified when in &#39;Submitted and pending approval&#39; state. Once the application is approved, the details cannot be changed using this method.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modifyLoanApplicationTest() throws ApiException {
        Long loanId = null;
        PutLoansLoanIdRequest body = null;
        PutLoansLoanIdResponse response = api.modifyLoanApplication(loanId, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postLoanRepaymentTemplateTest() throws ApiException {
        File file = null;
        String locale = null;
        String dateFormat = null;
        String response = api.postLoanRepaymentTemplate(file, locale, dateFormat);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postLoanTemplateTest() throws ApiException {
        File file = null;
        String locale = null;
        String dateFormat = null;
        String response = api.postLoanTemplate(file, locale, dateFormat);

        // TODO: test validations
    }
    
    /**
     * List Loans
     *
     * The list capability of loans can support pagination and sorting. Example Requests:  loans  loans?fields&#x3D;accountNo  loans?offset&#x3D;10&amp;limit&#x3D;50  loans?orderBy&#x3D;accountNo&amp;sortOrder&#x3D;DESC
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAllTest() throws ApiException {
        String sqlSearch = null;
        String externalId = null;
        Integer offset = null;
        Integer limit = null;
        String orderBy = null;
        String sortOrder = null;
        String accountNo = null;
        GetLoansResponse response = api.retrieveAll(sqlSearch, externalId, offset, limit, orderBy, sortOrder, accountNo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveApprovalTemplateTest() throws ApiException {
        Long loanId = null;
        String templateType = null;
        String response = api.retrieveApprovalTemplate(loanId, templateType);

        // TODO: test validations
    }
    
    /**
     * Retrieve a Loan
     *
     * Note: template&#x3D;true parameter doesn&#39;t apply to this resource.Example Requests:  loans/1   loans/1?fields&#x3D;id,principal,annualInterestRate   loans/1?associations&#x3D;all  loans/1?associations&#x3D;all&amp;exclude&#x3D;guarantors   loans/1?fields&#x3D;id,principal,annualInterestRate&amp;associations&#x3D;repaymentSchedule,transactions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveLoanTest() throws ApiException {
        Long loanId = null;
        Boolean staffInSelectedOfficeOnly = null;
        GetLoansLoanIdResponse response = api.retrieveLoan(loanId, staffInSelectedOfficeOnly);

        // TODO: test validations
    }
    
    /**
     * Approve Loan Application | Recover Loan Guarantee | Undo Loan Application Approval | Assign a Loan Officer | Unassign a Loan Officer | Reject Loan Application | Applicant Withdraws from Loan Application | Disburse Loan Disburse Loan To Savings Account | Undo Loan Disbursal
     *
     * Approve Loan Application: Mandatory Fields: approvedOnDate Optional Fields: approvedLoanAmount and expectedDisbursementDate Approves the loan application  Recover Loan Guarantee: Recovers the loan guarantee  Undo Loan Application Approval: Undoes the Loan Application Approval  Assign a Loan Officer: Allows you to assign Loan Officer for existing Loan.  Unassign a Loan Officer: Allows you to unassign the Loan Officer.  Reject Loan Application: Mandatory Fields: rejectedOnDate Allows you to reject the loan application  Applicant Withdraws from Loan Application: Mandatory Fields: withdrawnOnDate Allows the applicant to withdraw the loan application  Disburse Loan: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the Loan  Disburse Loan To Savings Account: Mandatory Fields: actualDisbursementDate Optional Fields: transactionAmount and fixedEmiAmount Disburses the loan to Saving Account  Undo Loan Disbursal: Undoes the Loan Disbursal Showing request and response for Assign a Loan Officer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void stateTransitionsTest() throws ApiException {
        Long loanId = null;
        PostLoansLoanIdRequest body = null;
        String command = null;
        PostLoansLoanIdResponse response = api.stateTransitions(loanId, body, command);

        // TODO: test validations
    }
    
    /**
     * Retrieve Loan Details Template
     *
     * This is a convenience resource. It can be useful when building maintenance user interface screens for client applications. The template data returned consists of any or all of:  Field Defaults Allowed Value Lists Example Requests:  loans/template?templateType&#x3D;individual&amp;clientId&#x3D;1   loans/template?templateType&#x3D;individual&amp;clientId&#x3D;1&amp;productId&#x3D;1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void templateTest() throws ApiException {
        Long clientId = null;
        Long groupId = null;
        Long productId = null;
        String templateType = null;
        Boolean staffInSelectedOfficeOnly = null;
        Boolean activeOnly = null;
        GetLoansTemplateResponse response = api.template(clientId, groupId, productId, templateType, staffInSelectedOfficeOnly, activeOnly);

        // TODO: test validations
    }
    
}
