/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteResourceTypeResourceIdNotesNoteIdResponse;
import io.swagger.client.model.GetResourceTypeResourceIdNotesNoteIdResponse;
import io.swagger.client.model.GetResourceTypeResourceIdNotesResponse;
import io.swagger.client.model.PostResourceTypeResourceIdNotesRequest;
import io.swagger.client.model.PostResourceTypeResourceIdNotesResponse;
import io.swagger.client.model.PutResourceTypeResourceIdNotesNoteIdRequest;
import io.swagger.client.model.PutResourceTypeResourceIdNotesNoteIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotesApi
 */
@Ignore
public class NotesApiTest {

    private final NotesApi api = new NotesApi();

    
    /**
     * Add a Resource Note
     *
     * Adds a new note to a supported resource.  Example Requests:  clients/1/notes   groups/1/notes
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addNewNoteTest() throws ApiException {
        String resourceType = null;
        Long resourceId = null;
        PostResourceTypeResourceIdNotesRequest body = null;
        PostResourceTypeResourceIdNotesResponse response = api.addNewNote(resourceType, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * Delete a Resource Note
     *
     * Deletes a Resource Note
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNoteTest() throws ApiException {
        String resourceType = null;
        Long resourceId = null;
        Long noteId = null;
        DeleteResourceTypeResourceIdNotesNoteIdResponse response = api.deleteNote(resourceType, resourceId, noteId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a Resource Note
     *
     * Retrieves a Resource Note  Example Requests:  clients/1/notes/76   groups/1/notes/20   clients/1/notes/76?fields&#x3D;note,createdOn,createdByUsername   groups/1/notes/20?fields&#x3D;note,createdOn,createdByUsername
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveNoteTest() throws ApiException {
        String resourceType = null;
        Long resourceId = null;
        Long noteId = null;
        GetResourceTypeResourceIdNotesNoteIdResponse response = api.retrieveNote(resourceType, resourceId, noteId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a Resource&#39;s Notes
     *
     * Retrieves a Resource&#39;s Notes  Note: Notes are returned in descending createOn order.  Example Requests:  clients/2/notes   groups/2/notes?fields&#x3D;note,createdOn,createdByUsername
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveNotesByResourceTest() throws ApiException {
        String resourceType = null;
        Long resourceId = null;
        List<GetResourceTypeResourceIdNotesResponse> response = api.retrieveNotesByResource(resourceType, resourceId);

        // TODO: test validations
    }
    
    /**
     * Update a Resource Note
     *
     * Updates a Resource Note
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNoteTest() throws ApiException {
        String resourceType = null;
        Long resourceId = null;
        Long noteId = null;
        PutResourceTypeResourceIdNotesNoteIdRequest body = null;
        PutResourceTypeResourceIdNotesNoteIdResponse response = api.updateNote(resourceType, resourceId, noteId, body);

        // TODO: test validations
    }
    
}
