/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTemplateResponse;
import io.swagger.client.model.GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse;
import io.swagger.client.model.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest;
import io.swagger.client.model.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsResponse;
import io.swagger.client.model.PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecurringDepositAccountTransactionsApi
 */
@Ignore
public class RecurringDepositAccountTransactionsApiTest {

    private final RecurringDepositAccountTransactionsApi api = new RecurringDepositAccountTransactionsApi();

    
    /**
     * Adjust Transaction | Undo transaction
     *
     * Adjust Transaction:  This command modifies the given transaction.  Undo transaction:  This command reverses the given transaction.  Showing request/response for &#39;Adjust Transaction&#39;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleTransactionCommandsTest() throws ApiException {
        Long recurringDepositAccountId = null;
        Long transactionId = null;
        PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest body = null;
        String command = null;
        PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse response = api.handleTransactionCommands(recurringDepositAccountId, transactionId, body, command);

        // TODO: test validations
    }
    
    /**
     * Retrieve Recurring Deposit Account Transaction
     *
     * Retrieves Recurring Deposit Account Transaction  Example Requests:  recurringdepositaccounts/1/transactions/1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveOneTest() throws ApiException {
        Long recurringDepositAccountId = null;
        Long transactionId = null;
        GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse response = api.retrieveOne(recurringDepositAccountId, transactionId);

        // TODO: test validations
    }
    
    /**
     * Retrieve Recurring Deposit Account Transaction Template
     *
     * This is a convenience resource. It can be useful when building maintenance user interface screens for client applications. The template data returned consists of any or all of:  Field Defaults Allowed Value Lists Example Requests:  recurringdepositaccounts/1/transactions/template?command&#x3D;deposit  recurringdepositaccounts/1/transactions/template?command&#x3D;withdrawal
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveTemplateTest() throws ApiException {
        Long recurringDepositAccountId = null;
        String command = null;
        GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTemplateResponse response = api.retrieveTemplate(recurringDepositAccountId, command);

        // TODO: test validations
    }
    
    /**
     * Deposit Transaction | Withdrawal Transaction
     *
     * Deposit Transaction:  Used for a deposit transaction  Withdrawal Transaction:  Used for a Withdrawal Transaction  Showing request/response for Deposit Transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionTest() throws ApiException {
        Long recurringDepositAccountId = null;
        PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest body = null;
        String command = null;
        PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsResponse response = api.transaction(recurringDepositAccountId, body, command);

        // TODO: test validations
    }
    
}
