/*
 * Apache Fineract API Documentation
 * Apache Fineract is a secure, multi-tenanted microfinance platform. <br />              The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform. The reference app [  https://demo.openmf.org  ] (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation.              <br/>The API                 is organized around REST [ https://en.wikipedia.org/wiki/Representational_state_transfer ]               <br/> Find out more about Apache Fineract on [ https://demo.openmf.org/api-docs/apiLive.htm#top ]              <br/> You can Try The API From Your Browser itself at [ https://demo.openmf.org/api-docs/apiLive.htm#interact ]              <br/> The Generic Options are available at [ https://demo.openmf.org/api-docs/apiLive.htm#genopts ]              <br/> Find out more about Updating Dates and Numbers at [ https://demo.openmf.org/api-docs/apiLive.htm#dates_and_numbers ]              <br/> For the Authentication and the Basic of HTTP and HTTPS refer [ https://demo.openmf.org/api-docs/apiLive.htm#authentication_overview ]              <br/> Check about ERROR codes at [ https://demo.openmf.org/api-docs/apiLive.htm#errors ]               <br/> <br/> Please refer to the old documentation for any documentation queries [ https://demo.openmf.org/api-docs/apiLive.htm ]              <br/>             ______________________________________________________________________________________________________________________________          
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DeleteSavingsProductsProductIdResponse;
import io.swagger.client.model.GetSavingsProductsProductIdResponse;
import io.swagger.client.model.GetSavingsProductsResponse;
import io.swagger.client.model.GetSavingsProductsTemplateResponse;
import io.swagger.client.model.PostSavingsProductsRequest;
import io.swagger.client.model.PostSavingsProductsResponse;
import io.swagger.client.model.PutSavingsProductsProductIdRequest;
import io.swagger.client.model.PutSavingsProductsProductIdResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SavingsProductApi
 */
@Ignore
public class SavingsProductApiTest {

    private final SavingsProductApi api = new SavingsProductApi();

    
    /**
     * Create a Savings Product
     *
     * Creates a Savings Product  Mandatory Fields: name, shortName, description, currencyCode, digitsAfterDecimal,inMultiplesOf, nominalAnnualInterestRate, interestCompoundingPeriodType, interestCalculationType, interestCalculationDaysInYearType,accountingRule  Mandatory Fields for Cash based accounting (accountingRule &#x3D; 2): savingsReferenceAccountId, savingsControlAccountId, interestOnSavingsAccountId, incomeFromFeeAccountId, transfersInSuspenseAccountId, incomeFromPenaltyAccountId  Optional Fields: minRequiredOpeningBalance, lockinPeriodFrequency, lockinPeriodFrequencyType, withdrawalFeeForTransfers, paymentChannelToFundSourceMappings, feeToIncomeAccountMappings, penaltyToIncomeAccountMappings, charges, allowOverdraft, overdraftLimit, minBalanceForInterestCalculation,withHoldTax,taxGroupId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        PostSavingsProductsRequest body = null;
        PostSavingsProductsResponse response = api.create(body);

        // TODO: test validations
    }
    
    /**
     * Delete a Savings Product
     *
     * Deletes a Savings Product
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        Long productId = null;
        DeleteSavingsProductsProductIdResponse response = api.delete(productId);

        // TODO: test validations
    }
    
    /**
     * List Savings Products
     *
     * Lists Savings Products  Example Requests:  savingsproducts  savingsproducts?fields&#x3D;name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAllTest() throws ApiException {
        List<GetSavingsProductsResponse> response = api.retrieveAll();

        // TODO: test validations
    }
    
    /**
     * Retrieve a Savings Product
     *
     * Retrieves a Savings Product  Example Requests:  savingsproducts/1  savingsproducts/1?template&#x3D;true  savingsproducts/1?fields&#x3D;name,description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveOneTest() throws ApiException {
        Long productId = null;
        GetSavingsProductsProductIdResponse response = api.retrieveOne(productId);

        // TODO: test validations
    }
    
    /**
     * Retrieve Savings Product Template
     *
     * This is a convenience resource. It can be useful when building maintenance user interface screens for client applications. The template data returned consists of any or all of:  Field Defaults Allowed Value Lists Example Request:  savingsproducts/template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveTemplateTest() throws ApiException {
        GetSavingsProductsTemplateResponse response = api.retrieveTemplate();

        // TODO: test validations
    }
    
    /**
     * Update a Savings Product
     *
     * Updates a Savings Product
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        Long productId = null;
        PutSavingsProductsProductIdRequest body = null;
        PutSavingsProductsProductIdResponse response = api.update(productId, body);

        // TODO: test validations
    }
    
}
