//
// AccountingRuleData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AccountingRuleData: Codable {

    public var creditTags: [AccountingTagRuleData]?
    public var debitTags: [AccountingTagRuleData]?

    public init(creditTags: [AccountingTagRuleData]?, debitTags: [AccountingTagRuleData]?) {
        self.creditTags = creditTags
        self.debitTags = debitTags
    }


}

