//
// AppUserClientMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppUserClientMapping: Codable {

    public var _id: Int64?
    public var client: Client?
    public var new: Bool?

    public init(_id: Int64?, client: Client?, new: Bool?) {
        self._id = _id
        self.client = client
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case client
        case new
    }


}

