//
// AppUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppUser: Codable {

    public var _id: Int64?
    public var email: String?
    public var username: String?
    public var firstname: String?
    public var lastname: String?
    public var password: String?
    public var accountNonExpired: Bool?
    public var accountNonLocked: Bool?
    public var credentialsNonExpired: Bool?
    public var enabled: Bool?
    public var deleted: Bool?
    public var office: Office?
    public var staff: Staff?
    public var roles: [Role]?
    public var lastTimePasswordUpdated: Date?
    public var passwordNeverExpires: Bool?
    public var appUserClientMappings: [AppUserClientMapping]?
    public var selfServiceUser: Bool?
    public var staffId: Int64?
    public var staffDisplayName: String?
    public var notEnabled: Bool?
    public var authorities: [GrantedAuthority]?
    public var new: Bool?

    public init(_id: Int64?, email: String?, username: String?, firstname: String?, lastname: String?, password: String?, accountNonExpired: Bool?, accountNonLocked: Bool?, credentialsNonExpired: Bool?, enabled: Bool?, deleted: Bool?, office: Office?, staff: Staff?, roles: [Role]?, lastTimePasswordUpdated: Date?, passwordNeverExpires: Bool?, appUserClientMappings: [AppUserClientMapping]?, selfServiceUser: Bool?, staffId: Int64?, staffDisplayName: String?, notEnabled: Bool?, authorities: [GrantedAuthority]?, new: Bool?) {
        self._id = _id
        self.email = email
        self.username = username
        self.firstname = firstname
        self.lastname = lastname
        self.password = password
        self.accountNonExpired = accountNonExpired
        self.accountNonLocked = accountNonLocked
        self.credentialsNonExpired = credentialsNonExpired
        self.enabled = enabled
        self.deleted = deleted
        self.office = office
        self.staff = staff
        self.roles = roles
        self.lastTimePasswordUpdated = lastTimePasswordUpdated
        self.passwordNeverExpires = passwordNeverExpires
        self.appUserClientMappings = appUserClientMappings
        self.selfServiceUser = selfServiceUser
        self.staffId = staffId
        self.staffDisplayName = staffDisplayName
        self.notEnabled = notEnabled
        self.authorities = authorities
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case email
        case username
        case firstname
        case lastname
        case password
        case accountNonExpired
        case accountNonLocked
        case credentialsNonExpired
        case enabled
        case deleted
        case office
        case staff
        case roles
        case lastTimePasswordUpdated
        case passwordNeverExpires
        case appUserClientMappings
        case selfServiceUser
        case staffId
        case staffDisplayName
        case notEnabled
        case authorities
        case new
    }


}

