//
// BatchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BatchResponse: Codable {

    public var requestId: Int64?
    public var statusCode: Int?
    public var headers: [Header]?
    public var body: String?

    public init(requestId: Int64?, statusCode: Int?, headers: [Header]?, body: String?) {
        self.requestId = requestId
        self.statusCode = statusCode
        self.headers = headers
        self.body = body
    }


}

