//
// Chronology.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Chronology: Codable {

    public var zone: DateTimeZone?

    public init(zone: DateTimeZone?) {
        self.zone = zone
    }


}

