//
// Client.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Client: Codable {

    public var _id: Int64?
    public var office: Office?
    public var transferToOffice: Office?
    public var image: Image?
    public var status: Int?
    public var firstname: String?
    public var middlename: String?
    public var lastname: String?
    public var displayName: String?
    public var externalId: String?
    public var staff: Staff?
    public var groups: [Group]?
    public var accountNumberRequiresAutoGeneration: Bool?
    public var closureDate: Date?
    public var withdrawalDate: Date?
    public var submittedOnDate: Date?
    public var legalForm: Int?
    public var reopenedDate: Date?
    public var proposedTransferDate: Date?
    public var active: Bool?
    public var closed: Bool?
    public var rejected: Bool?
    public var notPending: Bool?
    public var activationLocalDate: Date?
    public var transferInProgress: Bool?
    public var transferOnHold: Bool?
    public var transferInProgressOrOnHold: Bool?
    public var notStaff: Bool?
    public var rejectedDate: Date?
    public var withdrawn: Bool?
    public var officeJoiningLocalDate: Date?
    public var pending: Bool?
    public var notActive: Bool?
    public var new: Bool?

    public init(_id: Int64?, office: Office?, transferToOffice: Office?, image: Image?, status: Int?, firstname: String?, middlename: String?, lastname: String?, displayName: String?, externalId: String?, staff: Staff?, groups: [Group]?, accountNumberRequiresAutoGeneration: Bool?, closureDate: Date?, withdrawalDate: Date?, submittedOnDate: Date?, legalForm: Int?, reopenedDate: Date?, proposedTransferDate: Date?, active: Bool?, closed: Bool?, rejected: Bool?, notPending: Bool?, activationLocalDate: Date?, transferInProgress: Bool?, transferOnHold: Bool?, transferInProgressOrOnHold: Bool?, notStaff: Bool?, rejectedDate: Date?, withdrawn: Bool?, officeJoiningLocalDate: Date?, pending: Bool?, notActive: Bool?, new: Bool?) {
        self._id = _id
        self.office = office
        self.transferToOffice = transferToOffice
        self.image = image
        self.status = status
        self.firstname = firstname
        self.middlename = middlename
        self.lastname = lastname
        self.displayName = displayName
        self.externalId = externalId
        self.staff = staff
        self.groups = groups
        self.accountNumberRequiresAutoGeneration = accountNumberRequiresAutoGeneration
        self.closureDate = closureDate
        self.withdrawalDate = withdrawalDate
        self.submittedOnDate = submittedOnDate
        self.legalForm = legalForm
        self.reopenedDate = reopenedDate
        self.proposedTransferDate = proposedTransferDate
        self.active = active
        self.closed = closed
        self.rejected = rejected
        self.notPending = notPending
        self.activationLocalDate = activationLocalDate
        self.transferInProgress = transferInProgress
        self.transferOnHold = transferOnHold
        self.transferInProgressOrOnHold = transferInProgressOrOnHold
        self.notStaff = notStaff
        self.rejectedDate = rejectedDate
        self.withdrawn = withdrawn
        self.officeJoiningLocalDate = officeJoiningLocalDate
        self.pending = pending
        self.notActive = notActive
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case office
        case transferToOffice
        case image
        case status
        case firstname
        case middlename
        case lastname
        case displayName
        case externalId
        case staff
        case groups
        case accountNumberRequiresAutoGeneration
        case closureDate
        case withdrawalDate
        case submittedOnDate
        case legalForm
        case reopenedDate
        case proposedTransferDate
        case active
        case closed
        case rejected
        case notPending
        case activationLocalDate
        case transferInProgress
        case transferOnHold
        case transferInProgressOrOnHold
        case notStaff
        case rejectedDate
        case withdrawn
        case officeJoiningLocalDate
        case pending
        case notActive
        case new
    }


}

