//
// DeleteUsersUserIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeleteUsersUserIdResponse: Codable {

    public var officeId: Int64?
    public var resourceId: Int64?
    public var changes: DeleteUsersUserIdResponseChanges?

    public init(officeId: Int64?, resourceId: Int64?, changes: DeleteUsersUserIdResponseChanges?) {
        self.officeId = officeId
        self.resourceId = resourceId
        self.changes = changes
    }


}

