//
// DeletePaymentTypesPaymentTypeIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletePaymentTypesPaymentTypeIdResponse: Codable {

    public var resourceId: Int?

    public init(resourceId: Int?) {
        self.resourceId = resourceId
    }


}

