//
// DeleteLoansLoanIdChargesChargeIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeleteLoansLoanIdChargesChargeIdResponse: Codable {

    public var officeId: Int64?
    public var clientId: Int64?
    public var loanId: Int64?
    public var resourceId: Int?

    public init(officeId: Int64?, clientId: Int64?, loanId: Int64?, resourceId: Int?) {
        self.officeId = officeId
        self.clientId = clientId
        self.loanId = loanId
        self.resourceId = resourceId
    }


}

