//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Event: Codable {

    public var actionName: String?
    public var entityName: String?

    public init(actionName: String?, entityName: String?) {
        self.actionName = actionName
        self.entityName = entityName
    }


}

