//
// ExternalServicesPropertiesData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExternalServicesPropertiesData: Codable {

    public var name: String?
    public var value: String?

    public init(name: String?, value: String?) {
        self.name = name
        self.value = value
    }


}

