//
// Field.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Field: Codable {

    public var fieldName: String?
    public var fieldValue: String?
    public var fieldType: String?

    public init(fieldName: String?, fieldValue: String?, fieldType: String?) {
        self.fieldName = fieldName
        self.fieldValue = fieldValue
        self.fieldType = fieldType
    }


}

