//
// GetAccountTransfersTemplateRefundByTransferFromClient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccountTransfersTemplateRefundByTransferFromClient: Codable {

    public var _id: Int?
    public var accountNo: Int64?
    public var status: GetAccountTransfersStatus?
    public var active: Bool?
    public var activationDate: Date?
    public var firstname: String?
    public var lastname: String?
    public var displayName: String?
    public var gender: GetAccountTransfersGender?
    public var clientType: GetAccountTransfersClientType?
    public var clientClassification: GetAccountTransfersClientClassification?
    public var officeId: Int?
    public var officeName: String?
    public var timeline: GetAccountTransfersTimeline?
    public var groups: GetAccountTransfersGroups?

    public init(_id: Int?, accountNo: Int64?, status: GetAccountTransfersStatus?, active: Bool?, activationDate: Date?, firstname: String?, lastname: String?, displayName: String?, gender: GetAccountTransfersGender?, clientType: GetAccountTransfersClientType?, clientClassification: GetAccountTransfersClientClassification?, officeId: Int?, officeName: String?, timeline: GetAccountTransfersTimeline?, groups: GetAccountTransfersGroups?) {
        self._id = _id
        self.accountNo = accountNo
        self.status = status
        self.active = active
        self.activationDate = activationDate
        self.firstname = firstname
        self.lastname = lastname
        self.displayName = displayName
        self.gender = gender
        self.clientType = clientType
        self.clientClassification = clientClassification
        self.officeId = officeId
        self.officeName = officeName
        self.timeline = timeline
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountNo
        case status
        case active
        case activationDate
        case firstname
        case lastname
        case displayName
        case gender
        case clientType
        case clientClassification
        case officeId
        case officeName
        case timeline
        case groups
    }


}

