//
// GetAccountTransfersTemplateRefundByTransferResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccountTransfersTemplateRefundByTransferResponse: Codable {

    public var currency: GetAccountTransfersTemplateRefundByTransferCurrency?
    public var transferAmount: Float?
    public var transferDate: Date?
    public var fromOffice: GetAccountTransfersTemplateRefundByTransferFromOffice?
    public var fromClient: GetAccountTransfersTemplateRefundByTransferFromClient?
    public var fromAccountType: GetAccountTransfersPageItemsToAccountType?
    public var fromAccount: GetAccountTransfersTemplateRefundByTransferFromAccount?
    public var toOffice: GetAccountTransfersTemplateRefundByTransferFromOffice?
    public var toClient: GetAccountTransfersTemplateRefundByTransferToClient?
    public var toAccountType: GetAccountTransfersFromAccountType?
    public var toAccount: GetAccountTransfersTemplateRefundByTransferToAccount?
    public var fromOfficeOptions: [GetAccountTransfersTemplateRefundByTransferFromOfficeOptions]?
    public var fromClientOptions: [GetAccountTransfersTemplateRefundByTransferFromClientOptions]?
    public var fromAccountTypeOptions: [GetAccountTransfersFromAccountType]?
    public var fromAccountOptions: [GetAccountTransfersTemplateRefundByTransferFromAccountOptions]?
    public var toOfficeOptions: [GetAccountTransfersTemplateRefundByTransferFromOfficeOptions]?
    public var toClientOptions: [GetAccountTransfersTemplateRefundByTransferFromClientOptions]?
    public var toAccountTypeOptions: [GetAccountTransfersFromAccountType]?
    public var toAccountOptions: [GetAccountTransfersTemplateRefundByTransferToAccount]?

    public init(currency: GetAccountTransfersTemplateRefundByTransferCurrency?, transferAmount: Float?, transferDate: Date?, fromOffice: GetAccountTransfersTemplateRefundByTransferFromOffice?, fromClient: GetAccountTransfersTemplateRefundByTransferFromClient?, fromAccountType: GetAccountTransfersPageItemsToAccountType?, fromAccount: GetAccountTransfersTemplateRefundByTransferFromAccount?, toOffice: GetAccountTransfersTemplateRefundByTransferFromOffice?, toClient: GetAccountTransfersTemplateRefundByTransferToClient?, toAccountType: GetAccountTransfersFromAccountType?, toAccount: GetAccountTransfersTemplateRefundByTransferToAccount?, fromOfficeOptions: [GetAccountTransfersTemplateRefundByTransferFromOfficeOptions]?, fromClientOptions: [GetAccountTransfersTemplateRefundByTransferFromClientOptions]?, fromAccountTypeOptions: [GetAccountTransfersFromAccountType]?, fromAccountOptions: [GetAccountTransfersTemplateRefundByTransferFromAccountOptions]?, toOfficeOptions: [GetAccountTransfersTemplateRefundByTransferFromOfficeOptions]?, toClientOptions: [GetAccountTransfersTemplateRefundByTransferFromClientOptions]?, toAccountTypeOptions: [GetAccountTransfersFromAccountType]?, toAccountOptions: [GetAccountTransfersTemplateRefundByTransferToAccount]?) {
        self.currency = currency
        self.transferAmount = transferAmount
        self.transferDate = transferDate
        self.fromOffice = fromOffice
        self.fromClient = fromClient
        self.fromAccountType = fromAccountType
        self.fromAccount = fromAccount
        self.toOffice = toOffice
        self.toClient = toClient
        self.toAccountType = toAccountType
        self.toAccount = toAccount
        self.fromOfficeOptions = fromOfficeOptions
        self.fromClientOptions = fromClientOptions
        self.fromAccountTypeOptions = fromAccountTypeOptions
        self.fromAccountOptions = fromAccountOptions
        self.toOfficeOptions = toOfficeOptions
        self.toClientOptions = toClientOptions
        self.toAccountTypeOptions = toAccountTypeOptions
        self.toAccountOptions = toAccountOptions
    }


}

