//
// GetAccountsTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccountsTypeResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetAccountsPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetAccountsPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

