//
// GetAccountsSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccountsSummary: Codable {

    public var _id: Int?
    public var accountNo: Int64?
    public var totalApprovedShares: Int?
    public var totalPendingForApprovalShares: Int?
    public var productId: Int?
    public var productName: String?
    public var status: GetAccountsStatus?
    public var timeline: GetAccountsTimeline?
    public var currency: GetAccountsCurrency?

    public init(_id: Int?, accountNo: Int64?, totalApprovedShares: Int?, totalPendingForApprovalShares: Int?, productId: Int?, productName: String?, status: GetAccountsStatus?, timeline: GetAccountsTimeline?, currency: GetAccountsCurrency?) {
        self._id = _id
        self.accountNo = accountNo
        self.totalApprovedShares = totalApprovedShares
        self.totalPendingForApprovalShares = totalPendingForApprovalShares
        self.productId = productId
        self.productName = productName
        self.status = status
        self.timeline = timeline
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountNo
        case totalApprovedShares
        case totalPendingForApprovalShares
        case productId
        case productName
        case status
        case timeline
        case currency
    }


}

