//
// GetAccountTransfersTemplateRefundByTransferFromOffice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAccountTransfersTemplateRefundByTransferFromOffice: Codable {

    public var _id: Int?
    public var name: String?
    public var nameDecorated: String?
    public var externalId: Int?
    public var openingDate: Date?
    public var hierarchy: String?

    public init(_id: Int?, name: String?, nameDecorated: String?, externalId: Int?, openingDate: Date?, hierarchy: String?) {
        self._id = _id
        self.name = name
        self.nameDecorated = nameDecorated
        self.externalId = externalId
        self.openingDate = openingDate
        self.hierarchy = hierarchy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case nameDecorated
        case externalId
        case openingDate
        case hierarchy
    }


}

