//
// GetClientsClientIdIdentifiersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetClientsClientIdIdentifiersResponse: Codable {

    public var _id: Int?
    public var clientId: Int?
    public var documentType: GetClientsDocumentType?
    public var documentKey: String?
    public var _description: String?

    public init(_id: Int?, clientId: Int?, documentType: GetClientsDocumentType?, documentKey: String?, _description: String?) {
        self._id = _id
        self.clientId = clientId
        self.documentType = documentType
        self.documentKey = documentKey
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case clientId
        case documentType
        case documentKey
        case _description = "description"
    }


}

