//
// GetCodeValuesDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCodeValuesDataResponse: Codable {

    public var _id: Int64?
    public var name: String?
    public var _description: String?
    public var position: Int?

    public init(_id: Int64?, name: String?, _description: String?, position: Int?) {
        self._id = _id
        self.name = name
        self._description = _description
        self.position = position
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case position
    }


}

