//
// GetClientsDataTables.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetClientsDataTables: Codable {

    public var applicationTableName: String?
    public var registeredTableName: String?
    public var columnHeaderData: [GetClientsColumnHeaderData]?

    public init(applicationTableName: String?, registeredTableName: String?, columnHeaderData: [GetClientsColumnHeaderData]?) {
        self.applicationTableName = applicationTableName
        self.registeredTableName = registeredTableName
        self.columnHeaderData = columnHeaderData
    }


}

