//
// GetCentersPageItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCentersPageItems: Codable {

    public var _id: Int?
    public var status: GetCentersStatus?
    public var active: Bool?
    public var name: String?
    public var officeId: Int?
    public var officeName: String?
    public var hierarchy: String?

    public init(_id: Int?, status: GetCentersStatus?, active: Bool?, name: String?, officeId: Int?, officeName: String?, hierarchy: String?) {
        self._id = _id
        self.status = status
        self.active = active
        self.name = name
        self.officeId = officeId
        self.officeName = officeName
        self.hierarchy = hierarchy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case status
        case active
        case name
        case officeId
        case officeName
        case hierarchy
    }


}

