//
// GetClientsClientIdChargesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetClientsClientIdChargesResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetClientsChargesPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetClientsChargesPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

