//
// GetCentersTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCentersTemplateResponse: Codable {

    public var active: Bool?
    public var activationDate: Date?
    public var officeId: Int?
    public var officeOptions: [GetCentersOfficeOptions]?
    public var staffOptions: [GetCentersStaffOptions]?

    public init(active: Bool?, activationDate: Date?, officeId: Int?, officeOptions: [GetCentersOfficeOptions]?, staffOptions: [GetCentersStaffOptions]?) {
        self.active = active
        self.activationDate = activationDate
        self.officeId = officeId
        self.officeOptions = officeOptions
        self.staffOptions = staffOptions
    }


}

