//
// GetCachesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCachesResponse: Codable {

    public var cacheType: EnumOptionData?
    public var enabled: Bool?

    public init(cacheType: EnumOptionData?, enabled: Bool?) {
        self.cacheType = cacheType
        self.enabled = enabled
    }


}

