//
// GetCentersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCentersResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetCentersPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetCentersPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

