//
// GetCentersCenterIdAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCentersCenterIdAccountsResponse: Codable {

    public var savingsAccounts: [GetCentersSavingsAccounts]?

    public init(savingsAccounts: [GetCentersSavingsAccounts]?) {
        self.savingsAccounts = savingsAccounts
    }


}

