//
// GetCurrenciesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCurrenciesResponse: Codable {

    public var selectedCurrencyOptions: [CurrencyData]?
    public var currencyOptions: [CurrencyData]?

    public init(selectedCurrencyOptions: [CurrencyData]?, currencyOptions: [CurrencyData]?) {
        self.selectedCurrencyOptions = selectedCurrencyOptions
        self.currencyOptions = currencyOptions
    }


}

