//
// GetCentersTimeline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetCentersTimeline: Codable {

    public var submittedOnDate: Date?
    public var submittedByUsername: String?
    public var submittedByFirstname: String?
    public var submittedByLastname: String?

    public init(submittedOnDate: Date?, submittedByUsername: String?, submittedByFirstname: String?, submittedByLastname: String?) {
        self.submittedOnDate = submittedOnDate
        self.submittedByUsername = submittedByUsername
        self.submittedByFirstname = submittedByFirstname
        self.submittedByLastname = submittedByLastname
    }


}

