//
// GetChargesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetChargesResponse: Codable {

    public var _id: Int64?
    public var name: String?
    public var active: String?
    public var penalty: String?
    public var currency: GetChargesCurrencyResponse?
    public var amount: Float?
    public var chargeTimeType: GetChargesTimeTypeResponse?
    public var chargeAppliesTo: GetChargesAppliesToResponse?
    public var chargeCalculationType: GetChargesCalculationTypeResponse?
    public var chargePaymentMode: GetChargesPaymentModeResponse?

    public init(_id: Int64?, name: String?, active: String?, penalty: String?, currency: GetChargesCurrencyResponse?, amount: Float?, chargeTimeType: GetChargesTimeTypeResponse?, chargeAppliesTo: GetChargesAppliesToResponse?, chargeCalculationType: GetChargesCalculationTypeResponse?, chargePaymentMode: GetChargesPaymentModeResponse?) {
        self._id = _id
        self.name = name
        self.active = active
        self.penalty = penalty
        self.currency = currency
        self.amount = amount
        self.chargeTimeType = chargeTimeType
        self.chargeAppliesTo = chargeAppliesTo
        self.chargeCalculationType = chargeCalculationType
        self.chargePaymentMode = chargePaymentMode
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case active
        case penalty
        case currency
        case amount
        case chargeTimeType
        case chargeAppliesTo
        case chargeCalculationType
        case chargePaymentMode
    }


}

