//
// GetClientsPageItemsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetClientsPageItemsResponse: Codable {

    public var _id: Int?
    public var accountNo: String?
    public var status: GetClientStatus?
    public var active: Bool?
    public var fullname: String?
    public var displayName: String?
    public var officeId: Int?
    public var officeName: String?

    public init(_id: Int?, accountNo: String?, status: GetClientStatus?, active: Bool?, fullname: String?, displayName: String?, officeId: Int?, officeName: String?) {
        self._id = _id
        self.accountNo = accountNo
        self.status = status
        self.active = active
        self.fullname = fullname
        self.displayName = displayName
        self.officeId = officeId
        self.officeName = officeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountNo
        case status
        case active
        case fullname
        case displayName
        case officeId
        case officeName
    }


}

