//
// GetDataTablesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDataTablesResponse: Codable {

    public var appTableName: String?
    public var datatableName: String?
    public var column: [ResultsetColumnHeaderData]?

    public init(appTableName: String?, datatableName: String?, column: [ResultsetColumnHeaderData]?) {
        self.appTableName = appTableName
        self.datatableName = datatableName
        self.column = column
    }


}

