//
// GetDataTablesAppTableIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetDataTablesAppTableIdResponse: Codable {

    public var columnHeaders: [ResultsetColumnHeaderData]?
    public var data: [ResultsetRowData]?

    public init(columnHeaders: [ResultsetColumnHeaderData]?, data: [ResultsetRowData]?) {
        self.columnHeaders = columnHeaders
        self.data = data
    }


}

