//
// GetEntityTypeEntityIdDocumentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetEntityTypeEntityIdDocumentsResponse: Codable {

    public var _id: Int64?
    public var parentEntityType: String?
    public var parentEntityId: Int64?
    public var name: String?
    public var fileName: String?
    public var size: Int64?
    public var type: String?
    public var _description: String?
    public var location: String?
    public var storageType: Int?

    public init(_id: Int64?, parentEntityType: String?, parentEntityId: Int64?, name: String?, fileName: String?, size: Int64?, type: String?, _description: String?, location: String?, storageType: Int?) {
        self._id = _id
        self.parentEntityType = parentEntityType
        self.parentEntityId = parentEntityId
        self.name = name
        self.fileName = fileName
        self.size = size
        self.type = type
        self._description = _description
        self.location = location
        self.storageType = storageType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case parentEntityType
        case parentEntityId
        case name
        case fileName
        case size
        case type
        case _description = "description"
        case location
        case storageType
    }


}

