//
// GetEntityDatatableChecksTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetEntityDatatableChecksTemplateResponse: Codable {

    public var entities: [String]?
    public var statusClient: [DatatableCheckStatusData]?
    public var statusGroup: [DatatableCheckStatusData]?
    public var statusSavings: [DatatableCheckStatusData]?
    public var statusLoans: [DatatableCheckStatusData]?
    public var datatables: [DatatableChecksData]?
    public var loanProductDatas: [LoanProductData]?
    public var savingsProductDatas: [SavingsProductData]?

    public init(entities: [String]?, statusClient: [DatatableCheckStatusData]?, statusGroup: [DatatableCheckStatusData]?, statusSavings: [DatatableCheckStatusData]?, statusLoans: [DatatableCheckStatusData]?, datatables: [DatatableChecksData]?, loanProductDatas: [LoanProductData]?, savingsProductDatas: [SavingsProductData]?) {
        self.entities = entities
        self.statusClient = statusClient
        self.statusGroup = statusGroup
        self.statusSavings = statusSavings
        self.statusLoans = statusLoans
        self.datatables = datatables
        self.loanProductDatas = loanProductDatas
        self.savingsProductDatas = savingsProductDatas
    }


}

