//
// GetFixedDepositAccountsTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFixedDepositAccountsTemplateResponse: Codable {

    public var clientId: Int?
    public var clientName: String?
    public var productOptions: [GetFixedDepositAccountsProductOptions]?

    public init(clientId: Int?, clientName: String?, productOptions: [GetFixedDepositAccountsProductOptions]?) {
        self.clientId = clientId
        self.clientName = clientName
        self.productOptions = productOptions
    }


}

