//
// GetFieldConfigurationEntityResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFieldConfigurationEntityResponse: Codable {

    public var fieldConfigurationId: Int?
    public var entity: String?
    public var subentity: String?
    public var field: String?
    public var isEnabled: String?
    public var isMandatory: String?
    public var validationRegex: String?

    public init(fieldConfigurationId: Int?, entity: String?, subentity: String?, field: String?, isEnabled: String?, isMandatory: String?, validationRegex: String?) {
        self.fieldConfigurationId = fieldConfigurationId
        self.entity = entity
        self.subentity = subentity
        self.field = field
        self.isEnabled = isEnabled
        self.isMandatory = isMandatory
        self.validationRegex = validationRegex
    }

    public enum CodingKeys: String, CodingKey { 
        case fieldConfigurationId
        case entity
        case subentity
        case field
        case isEnabled = "is_enabled"
        case isMandatory = "is_mandatory"
        case validationRegex = "validation_regex"
    }


}

