//
// GetFixedDepositProductsProductIdFeeToIncomeAccountMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFixedDepositProductsProductIdFeeToIncomeAccountMappings: Codable {

    public var charge: GetFixedDepositProductsProductIdFeeToIncomeAccountMappingsCharge?
    public var incomeAccount: GetFixedDepositProductsProductIdFeeToIncomeAccountMappingsIncomeAccount?

    public init(charge: GetFixedDepositProductsProductIdFeeToIncomeAccountMappingsCharge?, incomeAccount: GetFixedDepositProductsProductIdFeeToIncomeAccountMappingsIncomeAccount?) {
        self.charge = charge
        self.incomeAccount = incomeAccount
    }


}

