//
// GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappings: Codable {

    public var charge: GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge?
    public var incomeAccount: GetFixedDepositProductsProductIdIncomeFromPenaltyAccount?

    public init(charge: GetFixedDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge?, incomeAccount: GetFixedDepositProductsProductIdIncomeFromPenaltyAccount?) {
        self.charge = charge
        self.incomeAccount = incomeAccount
    }


}

