//
// GetFromOfficeResponseStandingInstructionSwagger.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFromOfficeResponseStandingInstructionSwagger: Codable {

    public var _id: Int64?
    public var name: String?
    public var decoratedName: String?
    public var externalId: Int?
    public var openingDate: Date?
    public var hierarchy: String?

    public init(_id: Int64?, name: String?, decoratedName: String?, externalId: Int?, openingDate: Date?, hierarchy: String?) {
        self._id = _id
        self.name = name
        self.decoratedName = decoratedName
        self.externalId = externalId
        self.openingDate = openingDate
        self.hierarchy = hierarchy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case decoratedName
        case externalId
        case openingDate
        case hierarchy
    }


}

