//
// GetFinancialActivityAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFinancialActivityAccountsResponse: Codable {

    public var _id: Int64?
    public var financialActivityData: FinancialActivityData?
    public var glAccountData: GLAccountData?

    public init(_id: Int64?, financialActivityData: FinancialActivityData?, glAccountData: GLAccountData?) {
        self._id = _id
        self.financialActivityData = financialActivityData
        self.glAccountData = glAccountData
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case financialActivityData
        case glAccountData
    }


}

