//
// GetFixedDepositAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFixedDepositAccountsResponse: Codable {

    public var _id: Int?
    public var accountNo: Int64?
    public var clientId: Int?
    public var clientName: String?
    public var savingsProductId: Int?
    public var savingsProductName: String?
    public var fieldOfficerId: Int?
    public var status: GetFixedDepositAccountsStatus?
    public var timeline: GetFixedDepositAccountsTimeline?
    public var currency: GetFixedDepositAccountsCurrency?
    public var interestCompoundingPeriodType: GetFixedDepositAccountsInterestCompoundingPeriodType?
    public var interestPostingPeriodType: GetFixedDepositAccountsInterestPostingPeriodType?
    public var interestCalculationType: GetFixedDepositAccountsInterestCalculationType?
    public var interestCalculationDaysInYearType: GetFixedDepositAccountsInterestCalculationDaysInYearType?
    public var summary: GetFixedDepositAccountsSummary?
    public var interestFreePeriodApplicable: Bool?
    public var preClosurePenalApplicable: Bool?
    public var minDepositTerm: Int?
    public var maxDepositTerm: Int?
    public var minDepositTermType: GetFixedDepositAccountsMinDepositTermType?
    public var maxDepositTermType: GetFixedDepositAccountsMaxDepositTermType?
    public var depositAmount: Float?
    public var maturityAmount: Float?
    public var maturityDate: Date?
    public var depositPeriod: Int?
    public var depositPeriodFrequency: GetFixedDepositAccountsDepositPeriodFrequency?

    public init(_id: Int?, accountNo: Int64?, clientId: Int?, clientName: String?, savingsProductId: Int?, savingsProductName: String?, fieldOfficerId: Int?, status: GetFixedDepositAccountsStatus?, timeline: GetFixedDepositAccountsTimeline?, currency: GetFixedDepositAccountsCurrency?, interestCompoundingPeriodType: GetFixedDepositAccountsInterestCompoundingPeriodType?, interestPostingPeriodType: GetFixedDepositAccountsInterestPostingPeriodType?, interestCalculationType: GetFixedDepositAccountsInterestCalculationType?, interestCalculationDaysInYearType: GetFixedDepositAccountsInterestCalculationDaysInYearType?, summary: GetFixedDepositAccountsSummary?, interestFreePeriodApplicable: Bool?, preClosurePenalApplicable: Bool?, minDepositTerm: Int?, maxDepositTerm: Int?, minDepositTermType: GetFixedDepositAccountsMinDepositTermType?, maxDepositTermType: GetFixedDepositAccountsMaxDepositTermType?, depositAmount: Float?, maturityAmount: Float?, maturityDate: Date?, depositPeriod: Int?, depositPeriodFrequency: GetFixedDepositAccountsDepositPeriodFrequency?) {
        self._id = _id
        self.accountNo = accountNo
        self.clientId = clientId
        self.clientName = clientName
        self.savingsProductId = savingsProductId
        self.savingsProductName = savingsProductName
        self.fieldOfficerId = fieldOfficerId
        self.status = status
        self.timeline = timeline
        self.currency = currency
        self.interestCompoundingPeriodType = interestCompoundingPeriodType
        self.interestPostingPeriodType = interestPostingPeriodType
        self.interestCalculationType = interestCalculationType
        self.interestCalculationDaysInYearType = interestCalculationDaysInYearType
        self.summary = summary
        self.interestFreePeriodApplicable = interestFreePeriodApplicable
        self.preClosurePenalApplicable = preClosurePenalApplicable
        self.minDepositTerm = minDepositTerm
        self.maxDepositTerm = maxDepositTerm
        self.minDepositTermType = minDepositTermType
        self.maxDepositTermType = maxDepositTermType
        self.depositAmount = depositAmount
        self.maturityAmount = maturityAmount
        self.maturityDate = maturityDate
        self.depositPeriod = depositPeriod
        self.depositPeriodFrequency = depositPeriodFrequency
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountNo
        case clientId
        case clientName
        case savingsProductId
        case savingsProductName
        case fieldOfficerId
        case status
        case timeline
        case currency
        case interestCompoundingPeriodType
        case interestPostingPeriodType
        case interestCalculationType
        case interestCalculationDaysInYearType
        case summary
        case interestFreePeriodApplicable
        case preClosurePenalApplicable
        case minDepositTerm
        case maxDepositTerm
        case minDepositTermType
        case maxDepositTermType
        case depositAmount
        case maturityAmount
        case maturityDate
        case depositPeriod
        case depositPeriodFrequency
    }


}

