//
// GetGroupsGroupIdAccountsMemberLoanStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetGroupsGroupIdAccountsMemberLoanStatus: Codable {

    public var _id: Int?
    public var code: String?
    public var value: String?
    public var pendingApproval: Bool?
    public var waitingForDisbursal: Bool?
    public var active: Bool?
    public var closedObligationsMet: Bool?
    public var closedWrittenOff: Bool?
    public var closedRescheduled: Bool?
    public var closed: Bool?
    public var overpaid: Bool?

    public init(_id: Int?, code: String?, value: String?, pendingApproval: Bool?, waitingForDisbursal: Bool?, active: Bool?, closedObligationsMet: Bool?, closedWrittenOff: Bool?, closedRescheduled: Bool?, closed: Bool?, overpaid: Bool?) {
        self._id = _id
        self.code = code
        self.value = value
        self.pendingApproval = pendingApproval
        self.waitingForDisbursal = waitingForDisbursal
        self.active = active
        self.closedObligationsMet = closedObligationsMet
        self.closedWrittenOff = closedWrittenOff
        self.closedRescheduled = closedRescheduled
        self.closed = closed
        self.overpaid = overpaid
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case value
        case pendingApproval
        case waitingForDisbursal
        case active
        case closedObligationsMet
        case closedWrittenOff
        case closedRescheduled
        case closed
        case overpaid
    }


}

