//
// GetGLAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetGLAccountsResponse: Codable {

    public var _id: Int64?
    public var name: String?
    public var parentId: Int64?
    public var glCode: String?
    public var disabled: Bool?
    public var manualEntriesAllowed: Bool?
    public var type: EnumOptionData?
    public var usage: EnumOptionData?
    public var _description: String?
    public var nameDecorated: String?
    public var tagId: CodeValueData?
    public var organizationRunningBalance: Int64?

    public init(_id: Int64?, name: String?, parentId: Int64?, glCode: String?, disabled: Bool?, manualEntriesAllowed: Bool?, type: EnumOptionData?, usage: EnumOptionData?, _description: String?, nameDecorated: String?, tagId: CodeValueData?, organizationRunningBalance: Int64?) {
        self._id = _id
        self.name = name
        self.parentId = parentId
        self.glCode = glCode
        self.disabled = disabled
        self.manualEntriesAllowed = manualEntriesAllowed
        self.type = type
        self.usage = usage
        self._description = _description
        self.nameDecorated = nameDecorated
        self.tagId = tagId
        self.organizationRunningBalance = organizationRunningBalance
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case parentId
        case glCode
        case disabled
        case manualEntriesAllowed
        case type
        case usage
        case _description = "description"
        case nameDecorated
        case tagId
        case organizationRunningBalance
    }


}

