//
// GetGroupsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetGroupsResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetGroupsPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetGroupsPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

