//
// GetGroupsGroupIdTimeline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetGroupsGroupIdTimeline: Codable {

    public var activatedOnDate: Date?
    public var activatedByUsername: String?
    public var activatedByFirstname: String?
    public var activatedByLastname: String?

    public init(activatedOnDate: Date?, activatedByUsername: String?, activatedByFirstname: String?, activatedByLastname: String?) {
        self.activatedOnDate = activatedOnDate
        self.activatedByUsername = activatedByUsername
        self.activatedByFirstname = activatedByFirstname
        self.activatedByLastname = activatedByLastname
    }


}

