//
// GetHookResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetHookResponse: Codable {

    public var _id: Int64?
    public var name: String?
    public var displayName: String?
    public var isActive: Bool?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var templateId: Int64?
    public var templateName: String?
    public var events: [Event]?
    public var config: [Field]?

    public init(_id: Int64?, name: String?, displayName: String?, isActive: Bool?, createdAt: Date?, updatedAt: Date?, templateId: Int64?, templateName: String?, events: [Event]?, config: [Field]?) {
        self._id = _id
        self.name = name
        self.displayName = displayName
        self.isActive = isActive
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.templateId = templateId
        self.templateName = templateName
        self.events = events
        self.config = config
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case displayName
        case isActive
        case createdAt
        case updatedAt
        case templateId
        case templateName
        case events
        case config
    }


}

