//
// GetInterestRateChartsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetInterestRateChartsResponse: Codable {

    public var _id: Int?
    public var fromDate: Date?
    public var savingsProductId: Int?
    public var savingsProductName: String?
    public var chartSlabs: [GetInterestRateChartsChartSlabs]?

    public init(_id: Int?, fromDate: Date?, savingsProductId: Int?, savingsProductName: String?, chartSlabs: [GetInterestRateChartsChartSlabs]?) {
        self._id = _id
        self.fromDate = fromDate
        self.savingsProductId = savingsProductId
        self.savingsProductName = savingsProductName
        self.chartSlabs = chartSlabs
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case fromDate
        case savingsProductId
        case savingsProductName
        case chartSlabs
    }


}

