//
// GetInterestRateChartsTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetInterestRateChartsTemplateResponse: Codable {

    public var periodTypes: [GetInterestRateChartsTemplatePeriodTypes]?

    public init(periodTypes: [GetInterestRateChartsTemplatePeriodTypes]?) {
        self.periodTypes = periodTypes
    }


}

