//
// GetInterestRateChartsChartIdChartSlabsIncentives.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetInterestRateChartsChartIdChartSlabsIncentives: Codable {

    public var _id: Int?
    public var entityType: GetInterestRateChartsChartIdChartSlabsEntityType?
    public var attributeName: GetInterestRateChartsChartIdChartSlabsAttributeName?
    public var conditionType: GetInterestRateChartsChartIdChartSlabsConditionType?
    public var attributeValue: Int?
    public var attributeValueDesc: String?
    public var incentiveType: GetInterestRateChartsChartIdChartSlabsIncentiveType?
    public var amount: Float?

    public init(_id: Int?, entityType: GetInterestRateChartsChartIdChartSlabsEntityType?, attributeName: GetInterestRateChartsChartIdChartSlabsAttributeName?, conditionType: GetInterestRateChartsChartIdChartSlabsConditionType?, attributeValue: Int?, attributeValueDesc: String?, incentiveType: GetInterestRateChartsChartIdChartSlabsIncentiveType?, amount: Float?) {
        self._id = _id
        self.entityType = entityType
        self.attributeName = attributeName
        self.conditionType = conditionType
        self.attributeValue = attributeValue
        self.attributeValueDesc = attributeValueDesc
        self.incentiveType = incentiveType
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case entityType
        case attributeName
        case conditionType
        case attributeValue
        case attributeValueDesc
        case incentiveType
        case amount
    }


}

