//
// GetLoanProductsInterestRecalculationTemplateData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoanProductsInterestRecalculationTemplateData: Codable {

    public var interestRecalculationCompoundingType: GetLoanProductsInterestRecalculationCompoundingType?
    public var rescheduleStrategyType: GetLoanProductsRescheduleStrategyType?
    public var preClosureInterestCalculationStrategy: GetLoanProductsPreClosureInterestCalculationStrategy?

    public init(interestRecalculationCompoundingType: GetLoanProductsInterestRecalculationCompoundingType?, rescheduleStrategyType: GetLoanProductsRescheduleStrategyType?, preClosureInterestCalculationStrategy: GetLoanProductsPreClosureInterestCalculationStrategy?) {
        self.interestRecalculationCompoundingType = interestRecalculationCompoundingType
        self.rescheduleStrategyType = rescheduleStrategyType
        self.preClosureInterestCalculationStrategy = preClosureInterestCalculationStrategy
    }


}

