//
// GetLoansType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoansType: Codable {

    public var _id: Int?
    public var code: String?
    public var value: String?
    public var disbursement: Bool?
    public var repaymentAtDisbursement: Bool?
    public var repayment: Bool?
    public var contra: Bool?
    public var waiveInterest: Bool?
    public var waiveCharges: Bool?
    public var writeOff: Bool?
    public var recoveryRepayment: Bool?

    public init(_id: Int?, code: String?, value: String?, disbursement: Bool?, repaymentAtDisbursement: Bool?, repayment: Bool?, contra: Bool?, waiveInterest: Bool?, waiveCharges: Bool?, writeOff: Bool?, recoveryRepayment: Bool?) {
        self._id = _id
        self.code = code
        self.value = value
        self.disbursement = disbursement
        self.repaymentAtDisbursement = repaymentAtDisbursement
        self.repayment = repayment
        self.contra = contra
        self.waiveInterest = waiveInterest
        self.waiveCharges = waiveCharges
        self.writeOff = writeOff
        self.recoveryRepayment = recoveryRepayment
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case value
        case disbursement
        case repaymentAtDisbursement
        case repayment
        case contra
        case waiveInterest
        case waiveCharges
        case writeOff
        case recoveryRepayment
    }


}

