//
// GetLockPeriodTypeEnum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLockPeriodTypeEnum: Codable {

    public var _id: Int?
    public var value: String?

    public init(_id: Int?, value: String?) {
        self._id = _id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case value
    }


}

