//
// GetLoanChargeTemplateChargeOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoanChargeTemplateChargeOptions: Codable {

    public var _id: Int?
    public var name: String?
    public var active: Bool?
    public var penalty: Bool?
    public var currency: GetLoanChargeCurrency?
    public var amount: Float?
    public var chargeTimeType: GetLoanChargeTemplateChargeTimeType?
    public var chargeAppliesTo: GetLoanChargeTemplateChargeAppliesTo?
    public var chargeCalculationType: GetLoanChargeCalculationType?

    public init(_id: Int?, name: String?, active: Bool?, penalty: Bool?, currency: GetLoanChargeCurrency?, amount: Float?, chargeTimeType: GetLoanChargeTemplateChargeTimeType?, chargeAppliesTo: GetLoanChargeTemplateChargeAppliesTo?, chargeCalculationType: GetLoanChargeCalculationType?) {
        self._id = _id
        self.name = name
        self.active = active
        self.penalty = penalty
        self.currency = currency
        self.amount = amount
        self.chargeTimeType = chargeTimeType
        self.chargeAppliesTo = chargeAppliesTo
        self.chargeCalculationType = chargeCalculationType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case active
        case penalty
        case currency
        case amount
        case chargeTimeType
        case chargeAppliesTo
        case chargeCalculationType
    }


}

