//
// GetLoanProductsProductIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoanProductsProductIdResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var shortName: String?
    public var includeInBorrowerCycle: Bool?
    public var useBorrowerCycle: Bool?
    public var status: String?
    public var currency: GetLoanProductsCurrency?
    public var principal: Float?
    public var minPrincipal: Float?
    public var maxPrincipal: Float?
    public var numberOfRepayments: Int?
    public var repaymentEvery: Int?
    public var repaymentFrequencyType: GetLoanProductsRepaymentFrequencyType?
    public var interestRatePerPeriod: Float?
    public var interestRateFrequencyType: GetLoanProductsInterestRateFrequencyType?
    public var annualInterestRate: Float?
    public var amortizationType: GetLoanProductsAmortizationType?
    public var interestType: GetLoanProductsInterestTemplateType?
    public var interestCalculationPeriodType: GetLoansProductsInterestCalculationPeriodType?
    public var transactionProcessingStrategyId: Int?
    public var transactionProcessingStrategyName: String?
    public var charges: [Int]?
    public var productsPrincipalVariationsForBorrowerCycle: [GetLoanProductsPrincipalVariationsForBorrowerCycle]?
    public var interestRateVariationsForBorrowerCycle: [Int]?
    public var numberOfRepaymentVariationsForBorrowerCycle: [Int]?
    public var accountingRule: GetLoanProductsAccountingRule?
    public var accountingMappings: GetLoanAccountingMappings?
    public var paymentChannelToFundSourceMappings: [GetLoanPaymentChannelToFundSourceMappings]?
    public var feeToIncomeAccountMappings: [GetLoanFeeToIncomeAccountMappings]?
    public var multiDisburseLoan: Bool?
    public var maxTrancheCount: Int?
    public var outstandingLoanBalance: Float?
    public var overdueDaysForNPA: Int?
    public var principalThresholdForLastInstalment: Int?

    public init(_id: Int?, name: String?, shortName: String?, includeInBorrowerCycle: Bool?, useBorrowerCycle: Bool?, status: String?, currency: GetLoanProductsCurrency?, principal: Float?, minPrincipal: Float?, maxPrincipal: Float?, numberOfRepayments: Int?, repaymentEvery: Int?, repaymentFrequencyType: GetLoanProductsRepaymentFrequencyType?, interestRatePerPeriod: Float?, interestRateFrequencyType: GetLoanProductsInterestRateFrequencyType?, annualInterestRate: Float?, amortizationType: GetLoanProductsAmortizationType?, interestType: GetLoanProductsInterestTemplateType?, interestCalculationPeriodType: GetLoansProductsInterestCalculationPeriodType?, transactionProcessingStrategyId: Int?, transactionProcessingStrategyName: String?, charges: [Int]?, productsPrincipalVariationsForBorrowerCycle: [GetLoanProductsPrincipalVariationsForBorrowerCycle]?, interestRateVariationsForBorrowerCycle: [Int]?, numberOfRepaymentVariationsForBorrowerCycle: [Int]?, accountingRule: GetLoanProductsAccountingRule?, accountingMappings: GetLoanAccountingMappings?, paymentChannelToFundSourceMappings: [GetLoanPaymentChannelToFundSourceMappings]?, feeToIncomeAccountMappings: [GetLoanFeeToIncomeAccountMappings]?, multiDisburseLoan: Bool?, maxTrancheCount: Int?, outstandingLoanBalance: Float?, overdueDaysForNPA: Int?, principalThresholdForLastInstalment: Int?) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self.includeInBorrowerCycle = includeInBorrowerCycle
        self.useBorrowerCycle = useBorrowerCycle
        self.status = status
        self.currency = currency
        self.principal = principal
        self.minPrincipal = minPrincipal
        self.maxPrincipal = maxPrincipal
        self.numberOfRepayments = numberOfRepayments
        self.repaymentEvery = repaymentEvery
        self.repaymentFrequencyType = repaymentFrequencyType
        self.interestRatePerPeriod = interestRatePerPeriod
        self.interestRateFrequencyType = interestRateFrequencyType
        self.annualInterestRate = annualInterestRate
        self.amortizationType = amortizationType
        self.interestType = interestType
        self.interestCalculationPeriodType = interestCalculationPeriodType
        self.transactionProcessingStrategyId = transactionProcessingStrategyId
        self.transactionProcessingStrategyName = transactionProcessingStrategyName
        self.charges = charges
        self.productsPrincipalVariationsForBorrowerCycle = productsPrincipalVariationsForBorrowerCycle
        self.interestRateVariationsForBorrowerCycle = interestRateVariationsForBorrowerCycle
        self.numberOfRepaymentVariationsForBorrowerCycle = numberOfRepaymentVariationsForBorrowerCycle
        self.accountingRule = accountingRule
        self.accountingMappings = accountingMappings
        self.paymentChannelToFundSourceMappings = paymentChannelToFundSourceMappings
        self.feeToIncomeAccountMappings = feeToIncomeAccountMappings
        self.multiDisburseLoan = multiDisburseLoan
        self.maxTrancheCount = maxTrancheCount
        self.outstandingLoanBalance = outstandingLoanBalance
        self.overdueDaysForNPA = overdueDaysForNPA
        self.principalThresholdForLastInstalment = principalThresholdForLastInstalment
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName
        case includeInBorrowerCycle
        case useBorrowerCycle
        case status
        case currency
        case principal
        case minPrincipal
        case maxPrincipal
        case numberOfRepayments
        case repaymentEvery
        case repaymentFrequencyType
        case interestRatePerPeriod
        case interestRateFrequencyType
        case annualInterestRate
        case amortizationType
        case interestType
        case interestCalculationPeriodType
        case transactionProcessingStrategyId
        case transactionProcessingStrategyName
        case charges
        case productsPrincipalVariationsForBorrowerCycle
        case interestRateVariationsForBorrowerCycle
        case numberOfRepaymentVariationsForBorrowerCycle
        case accountingRule
        case accountingMappings
        case paymentChannelToFundSourceMappings
        case feeToIncomeAccountMappings
        case multiDisburseLoan
        case maxTrancheCount
        case outstandingLoanBalance
        case overdueDaysForNPA
        case principalThresholdForLastInstalment
    }


}

