//
// GetLoansLoanIdDisbursementDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoansLoanIdDisbursementDetails: Codable {

    public var _id: Int?
    public var expectedDisbursementDate: Date?
    public var principal: Float?
    public var approvedPrincipal: Float?

    public init(_id: Int?, expectedDisbursementDate: Date?, principal: Float?, approvedPrincipal: Float?) {
        self._id = _id
        self.expectedDisbursementDate = expectedDisbursementDate
        self.principal = principal
        self.approvedPrincipal = approvedPrincipal
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case expectedDisbursementDate
        case principal
        case approvedPrincipal
    }


}

