//
// GetLoanProductsPrincipalVariationsForBorrowerCycle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoanProductsPrincipalVariationsForBorrowerCycle: Codable {

    public var _id: Int?
    public var borrowerCycleNumber: Int?
    public var paramType: GetLoanProductsParamType?
    public var valueConditionType: GetLoanProductsValueConditionType?
    public var minValue: Float?
    public var maxValue: Float?
    public var defaultValue: Float?

    public init(_id: Int?, borrowerCycleNumber: Int?, paramType: GetLoanProductsParamType?, valueConditionType: GetLoanProductsValueConditionType?, minValue: Float?, maxValue: Float?, defaultValue: Float?) {
        self._id = _id
        self.borrowerCycleNumber = borrowerCycleNumber
        self.paramType = paramType
        self.valueConditionType = valueConditionType
        self.minValue = minValue
        self.maxValue = maxValue
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case borrowerCycleNumber
        case paramType
        case valueConditionType
        case minValue
        case maxValue
        case defaultValue
    }


}

