//
// GetLoansResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLoansResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetLoansLoanIdResponse]?

    public init(totalFilteredRecords: Int?, pageItems: [GetLoansLoanIdResponse]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

