//
// GetOfficesTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetOfficesTemplateResponse: Codable {

    public var openingDate: Date?
    public var allowedParents: [GetOfficesResponse]?

    public init(openingDate: Date?, allowedParents: [GetOfficesResponse]?) {
        self.openingDate = openingDate
        self.allowedParents = allowedParents
    }


}

