//
// GetProvisioningCriteriaCriteriaIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetProvisioningCriteriaCriteriaIdResponse: Codable {

    public var criteriaId: Int64?
    public var criteriaName: String?
    public var createdBy: String?
    public var loanProducts: [LoanProductData]?
    public var provisioningcriteria: [ProvisioningCriteriaDefinitionData]?

    public init(criteriaId: Int64?, criteriaName: String?, createdBy: String?, loanProducts: [LoanProductData]?, provisioningcriteria: [ProvisioningCriteriaDefinitionData]?) {
        self.criteriaId = criteriaId
        self.criteriaName = criteriaName
        self.createdBy = createdBy
        self.loanProducts = loanProducts
        self.provisioningcriteria = provisioningcriteria
    }


}

