//
// GetProductsPageItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetProductsPageItems: Codable {

    public var _id: Int?
    public var name: String?
    public var shortName: String?
    public var totalShares: Int?

    public init(_id: Int?, name: String?, shortName: String?, totalShares: Int?) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self.totalShares = totalShares
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName
        case totalShares
    }


}

