//
// GetProvisioningCriteriaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetProvisioningCriteriaResponse: Codable {

    public var criteriaId: Int64?
    public var criteriaName: String?
    public var createdBy: String?

    public init(criteriaId: Int64?, criteriaName: String?, createdBy: String?) {
        self.criteriaId = criteriaId
        self.criteriaName = criteriaName
        self.createdBy = createdBy
    }


}

