//
// GetPasswordPreferencesTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetPasswordPreferencesTemplateResponse: Codable {

    public var _id: Int64?
    public var _description: String?
    public var active: Bool?
    public var key: String?

    public init(_id: Int64?, _description: String?, active: Bool?, key: String?) {
        self._id = _id
        self._description = _description
        self.active = active
        self.key = key
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case active
        case key
    }


}

