//
// GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings: Codable {

    public var charge: GetRecurringDepositProductsProductIdFeeToIncomeAccountMappingsCharge?
    public var incomeAccount: GetRecurringDepositProductsProductIdFeeToIncomeAccountMappingsIncomeAccount?

    public init(charge: GetRecurringDepositProductsProductIdFeeToIncomeAccountMappingsCharge?, incomeAccount: GetRecurringDepositProductsProductIdFeeToIncomeAccountMappingsIncomeAccount?) {
        self.charge = charge
        self.incomeAccount = incomeAccount
    }


}

