//
// GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositAccountsRecurringDepositAccountIdTransactionsTransactionIdResponse: Codable {

    public var _id: Int?
    public var transactionType: GetRecurringTransactionsTransactionType?
    public var accountId: Int?
    public var accountNo: String?
    public var date: Date?
    public var currency: GetRecurringTransactionsCurrency?
    public var paymentDetailData: GetRecurringPaymentDetailData?
    public var amount: Float?
    public var runningBalance: Int?
    public var reversed: Bool?

    public init(_id: Int?, transactionType: GetRecurringTransactionsTransactionType?, accountId: Int?, accountNo: String?, date: Date?, currency: GetRecurringTransactionsCurrency?, paymentDetailData: GetRecurringPaymentDetailData?, amount: Float?, runningBalance: Int?, reversed: Bool?) {
        self._id = _id
        self.transactionType = transactionType
        self.accountId = accountId
        self.accountNo = accountNo
        self.date = date
        self.currency = currency
        self.paymentDetailData = paymentDetailData
        self.amount = amount
        self.runningBalance = runningBalance
        self.reversed = reversed
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case transactionType
        case accountId
        case accountNo
        case date
        case currency
        case paymentDetailData
        case amount
        case runningBalance
        case reversed
    }


}

