//
// GetRecurringDepositAccountsTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositAccountsTemplateResponse: Codable {

    public var clientId: Int?
    public var clientName: String?
    public var productOptions: [GetRecurringProductOptions]?

    public init(clientId: Int?, clientName: String?, productOptions: [GetRecurringProductOptions]?) {
        self.clientId = clientId
        self.clientName = clientName
        self.productOptions = productOptions
    }


}

