//
// GetRecurringDepositProductsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositProductsResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var shortName: String?
    public var _description: String?
    public var currency: GetRecurringDepositProductsCurrency?
    public var recurringDepositFrequency: Int?
    public var recurringDepositFrequencyType: GetRecurringDepositProductsRecurringDepositFrequencyType?
    public var preClosurePenalApplicable: Bool?
    public var minDepositTerm: Int?
    public var maxDepositTerm: Int?
    public var minDepositTermType: GetRecurringDepositProductsMinDepositTermType?
    public var maxDepositTermType: GetRecurringDepositProductsMaxDepositTermType?
    public var nominalAnnualInterestRate: Double?
    public var interestCompoundingPeriodType: GetRecurringDepositProductsInterestCompoundingPeriodType?
    public var interestPostingPeriodType: GetRecurringDepositProductsInterestPostingPeriodType?
    public var interestCalculationType: GetRecurringDepositProductsInterestCalculationType?
    public var interestCalculationDaysInYearType: GetRecurringDepositProductsInterestCalculationDaysInYearType?
    public var accountingRule: GetRecurringDepositProductsAccountingRule?

    public init(_id: Int?, name: String?, shortName: String?, _description: String?, currency: GetRecurringDepositProductsCurrency?, recurringDepositFrequency: Int?, recurringDepositFrequencyType: GetRecurringDepositProductsRecurringDepositFrequencyType?, preClosurePenalApplicable: Bool?, minDepositTerm: Int?, maxDepositTerm: Int?, minDepositTermType: GetRecurringDepositProductsMinDepositTermType?, maxDepositTermType: GetRecurringDepositProductsMaxDepositTermType?, nominalAnnualInterestRate: Double?, interestCompoundingPeriodType: GetRecurringDepositProductsInterestCompoundingPeriodType?, interestPostingPeriodType: GetRecurringDepositProductsInterestPostingPeriodType?, interestCalculationType: GetRecurringDepositProductsInterestCalculationType?, interestCalculationDaysInYearType: GetRecurringDepositProductsInterestCalculationDaysInYearType?, accountingRule: GetRecurringDepositProductsAccountingRule?) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self._description = _description
        self.currency = currency
        self.recurringDepositFrequency = recurringDepositFrequency
        self.recurringDepositFrequencyType = recurringDepositFrequencyType
        self.preClosurePenalApplicable = preClosurePenalApplicable
        self.minDepositTerm = minDepositTerm
        self.maxDepositTerm = maxDepositTerm
        self.minDepositTermType = minDepositTermType
        self.maxDepositTermType = maxDepositTermType
        self.nominalAnnualInterestRate = nominalAnnualInterestRate
        self.interestCompoundingPeriodType = interestCompoundingPeriodType
        self.interestPostingPeriodType = interestPostingPeriodType
        self.interestCalculationType = interestCalculationType
        self.interestCalculationDaysInYearType = interestCalculationDaysInYearType
        self.accountingRule = accountingRule
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName
        case _description = "description"
        case currency
        case recurringDepositFrequency
        case recurringDepositFrequencyType
        case preClosurePenalApplicable
        case minDepositTerm
        case maxDepositTerm
        case minDepositTermType
        case maxDepositTermType
        case nominalAnnualInterestRate
        case interestCompoundingPeriodType
        case interestPostingPeriodType
        case interestCalculationType
        case interestCalculationDaysInYearType
        case accountingRule
    }


}

