//
// GetRecurringPaymentDetailData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringPaymentDetailData: Codable {

    public var _id: Int?
    public var paymentType: GetRecurringPaymentType?
    public var accountNumber: Int?
    public var checkNumber: Int?
    public var routingCode: Int?
    public var receiptNumber: Int?
    public var bankNumber: Int?

    public init(_id: Int?, paymentType: GetRecurringPaymentType?, accountNumber: Int?, checkNumber: Int?, routingCode: Int?, receiptNumber: Int?, bankNumber: Int?) {
        self._id = _id
        self.paymentType = paymentType
        self.accountNumber = accountNumber
        self.checkNumber = checkNumber
        self.routingCode = routingCode
        self.receiptNumber = receiptNumber
        self.bankNumber = bankNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case paymentType
        case accountNumber
        case checkNumber
        case routingCode
        case receiptNumber
        case bankNumber
    }


}

