//
// GetRecurringDepositProductsProductIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositProductsProductIdResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var shortName: String?
    public var _description: String?
    public var currency: GetRecurringDepositProductsProductIdCurrency?
    public var interestCompoundingPeriodType: GetRecurringDepositProductsProductIdInterestCompoundingPeriodType?
    public var interestPostingPeriodType: GetRecurringDepositProductsInterestPostingPeriodType?
    public var interestCalculationType: GetRecurringDepositProductsInterestCalculationType?
    public var interestCalculationDaysInYearType: GetRecurringDepositProductsInterestCalculationDaysInYearType?
    public var accountingMappings: GetRecurringDepositProductsProductIdAccountingMappings?
    public var feeToIncomeAccountMappings: [GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings]?
    public var penaltyToIncomeAccountMappings: [GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings]?
    public var recurringDepositFrequency: Int?
    public var recurringDepositFrequencyType: GetRecurringDepositProductsRecurringDepositFrequencyType?
    public var preClosurePenalApplicable: Bool?
    public var preClosurePenalInterest: Double?
    public var preClosurePenalInterestOnType: GetRecurringDepositProductsProductIdPreClosurePenalInterestOnType?
    public var minDepositTerm: Int?
    public var minDepositTermType: GetRecurringDepositProductsProductIdMinDepositTermType?
    public var maxDepositTerm: Int?
    public var maxDepositTermType: GetRecurringDepositProductsProductIdMaxDepositTermType?
    public var activeChart: GetRecurringDepositProductsProductIdActiveChart?

    public init(_id: Int?, name: String?, shortName: String?, _description: String?, currency: GetRecurringDepositProductsProductIdCurrency?, interestCompoundingPeriodType: GetRecurringDepositProductsProductIdInterestCompoundingPeriodType?, interestPostingPeriodType: GetRecurringDepositProductsInterestPostingPeriodType?, interestCalculationType: GetRecurringDepositProductsInterestCalculationType?, interestCalculationDaysInYearType: GetRecurringDepositProductsInterestCalculationDaysInYearType?, accountingMappings: GetRecurringDepositProductsProductIdAccountingMappings?, feeToIncomeAccountMappings: [GetRecurringDepositProductsProductIdFeeToIncomeAccountMappings]?, penaltyToIncomeAccountMappings: [GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings]?, recurringDepositFrequency: Int?, recurringDepositFrequencyType: GetRecurringDepositProductsRecurringDepositFrequencyType?, preClosurePenalApplicable: Bool?, preClosurePenalInterest: Double?, preClosurePenalInterestOnType: GetRecurringDepositProductsProductIdPreClosurePenalInterestOnType?, minDepositTerm: Int?, minDepositTermType: GetRecurringDepositProductsProductIdMinDepositTermType?, maxDepositTerm: Int?, maxDepositTermType: GetRecurringDepositProductsProductIdMaxDepositTermType?, activeChart: GetRecurringDepositProductsProductIdActiveChart?) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self._description = _description
        self.currency = currency
        self.interestCompoundingPeriodType = interestCompoundingPeriodType
        self.interestPostingPeriodType = interestPostingPeriodType
        self.interestCalculationType = interestCalculationType
        self.interestCalculationDaysInYearType = interestCalculationDaysInYearType
        self.accountingMappings = accountingMappings
        self.feeToIncomeAccountMappings = feeToIncomeAccountMappings
        self.penaltyToIncomeAccountMappings = penaltyToIncomeAccountMappings
        self.recurringDepositFrequency = recurringDepositFrequency
        self.recurringDepositFrequencyType = recurringDepositFrequencyType
        self.preClosurePenalApplicable = preClosurePenalApplicable
        self.preClosurePenalInterest = preClosurePenalInterest
        self.preClosurePenalInterestOnType = preClosurePenalInterestOnType
        self.minDepositTerm = minDepositTerm
        self.minDepositTermType = minDepositTermType
        self.maxDepositTerm = maxDepositTerm
        self.maxDepositTermType = maxDepositTermType
        self.activeChart = activeChart
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName
        case _description = "description"
        case currency
        case interestCompoundingPeriodType
        case interestPostingPeriodType
        case interestCalculationType
        case interestCalculationDaysInYearType
        case accountingMappings
        case feeToIncomeAccountMappings
        case penaltyToIncomeAccountMappings
        case recurringDepositFrequency
        case recurringDepositFrequencyType
        case preClosurePenalApplicable
        case preClosurePenalInterest
        case preClosurePenalInterestOnType
        case minDepositTerm
        case minDepositTermType
        case maxDepositTerm
        case maxDepositTermType
        case activeChart
    }


}

