//
// GetRecurringDepositProductsProductIdChartSlabs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositProductsProductIdChartSlabs: Codable {

    public var _id: Int?
    public var _description: String?
    public var periodType: GetRecurringDepositProductsProductIdPeriodType?
    public var fromPeriod: Int?
    public var toPeriod: Int?
    public var annualInterestRate: Double?
    public var currency: GetRecurringDepositProductsProductIdCurrency?

    public init(_id: Int?, _description: String?, periodType: GetRecurringDepositProductsProductIdPeriodType?, fromPeriod: Int?, toPeriod: Int?, annualInterestRate: Double?, currency: GetRecurringDepositProductsProductIdCurrency?) {
        self._id = _id
        self._description = _description
        self.periodType = periodType
        self.fromPeriod = fromPeriod
        self.toPeriod = toPeriod
        self.annualInterestRate = annualInterestRate
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case periodType
        case fromPeriod
        case toPeriod
        case annualInterestRate
        case currency
    }


}

