//
// GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappings: Codable {

    public var charge: GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge?
    public var incomeAccount: GetRecurringDepositProductsProductIdIncomeFromPenaltyAccount?

    public init(charge: GetRecurringDepositProductsProductIdPenaltyToIncomeAccountMappingsCharge?, incomeAccount: GetRecurringDepositProductsProductIdIncomeFromPenaltyAccount?) {
        self.charge = charge
        self.incomeAccount = incomeAccount
    }


}

