//
// GetSelfLoansTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfLoansTemplateResponse: Codable {

    public var clientId: Int?
    public var clientName: String?
    public var clientOfficeId: Int?
    public var timeline: GetSelfLoansTimeline?
    public var productOptions: [GetSelfLoansProductOptions]?

    public init(clientId: Int?, clientName: String?, clientOfficeId: Int?, timeline: GetSelfLoansTimeline?, productOptions: [GetSelfLoansProductOptions]?) {
        self.clientId = clientId
        self.clientName = clientName
        self.clientOfficeId = clientOfficeId
        self.timeline = timeline
        self.productOptions = productOptions
    }


}

