//
// GetSelfSavingsSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfSavingsSummary: Codable {

    public var currency: GetSelfSavingsCurrency?
    public var accountBalance: Int?

    public init(currency: GetSelfSavingsCurrency?, accountBalance: Int?) {
        self.currency = currency
        self.accountBalance = accountBalance
    }


}

