//
// GetSavingsProductsAccountingMappingOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsProductsAccountingMappingOptions: Codable {

    public var liabilityAccountOptions: [GetSavingsProductsLiabilityAccountOptions]?
    public var assetAccountOptions: [GetSavingsProductsAssetAccountOptions]?
    public var expenseAccountOptions: [GetSavingsProductsExpenseAccountOptions]?
    public var incomeAccountOptions: [GetSavingsProductsIncomeAccountOptions]?

    public init(liabilityAccountOptions: [GetSavingsProductsLiabilityAccountOptions]?, assetAccountOptions: [GetSavingsProductsAssetAccountOptions]?, expenseAccountOptions: [GetSavingsProductsExpenseAccountOptions]?, incomeAccountOptions: [GetSavingsProductsIncomeAccountOptions]?) {
        self.liabilityAccountOptions = liabilityAccountOptions
        self.assetAccountOptions = assetAccountOptions
        self.expenseAccountOptions = expenseAccountOptions
        self.incomeAccountOptions = incomeAccountOptions
    }


}

