//
// GetSavingsProductsChargeOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsProductsChargeOptions: Codable {

    public var active: Bool?
    public var amount: Int64?
    public var chargeAppliesTo: GetSavingsProductsChargeAppliesTo?
    public var chargeCalculationType: GetSavingsChargeCalculationType?
    public var chargePaymentMode: GetSavingsChargePaymentMode?
    public var chargeTimeType: GetSavingsChargeTimeType?
    public var currency: GetSavingsCurrency?
    public var _id: Int?
    public var name: String?
    public var penalty: Bool?

    public init(active: Bool?, amount: Int64?, chargeAppliesTo: GetSavingsProductsChargeAppliesTo?, chargeCalculationType: GetSavingsChargeCalculationType?, chargePaymentMode: GetSavingsChargePaymentMode?, chargeTimeType: GetSavingsChargeTimeType?, currency: GetSavingsCurrency?, _id: Int?, name: String?, penalty: Bool?) {
        self.active = active
        self.amount = amount
        self.chargeAppliesTo = chargeAppliesTo
        self.chargeCalculationType = chargeCalculationType
        self.chargePaymentMode = chargePaymentMode
        self.chargeTimeType = chargeTimeType
        self.currency = currency
        self._id = _id
        self.name = name
        self.penalty = penalty
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case amount
        case chargeAppliesTo
        case chargeCalculationType
        case chargePaymentMode
        case chargeTimeType
        case currency
        case _id = "id"
        case name
        case penalty
    }


}

