//
// GetSavingsProductsPaymentChannelToFundSourceMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsProductsPaymentChannelToFundSourceMappings: Codable {

    public var paymentType: GetSavingsProductsPaymentType?
    public var fundSourceAccount: GetSavingsProductsFundSourceAccount?

    public init(paymentType: GetSavingsProductsPaymentType?, fundSourceAccount: GetSavingsProductsFundSourceAccount?) {
        self.paymentType = paymentType
        self.fundSourceAccount = fundSourceAccount
    }


}

