//
// GetSelfBeneficiariesTPTResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfBeneficiariesTPTResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var officeName: String?
    public var clientName: String?
    public var accountType: GetSelfBeneficiariesAccountOptions?
    public var accountNumber: Int64?
    public var transferLimit: Int?

    public init(_id: Int?, name: String?, officeName: String?, clientName: String?, accountType: GetSelfBeneficiariesAccountOptions?, accountNumber: Int64?, transferLimit: Int?) {
        self._id = _id
        self.name = name
        self.officeName = officeName
        self.clientName = clientName
        self.accountType = accountType
        self.accountNumber = accountNumber
        self.transferLimit = transferLimit
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case officeName
        case clientName
        case accountType
        case accountNumber
        case transferLimit
    }


}

