//
// GetSavingsProductsFeeToIncomeAccountMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsProductsFeeToIncomeAccountMappings: Codable {

    public var charge: GetSavingsProductsFeeToIncomeAccountMappingsCharge?
    public var incomeAccount: GetSavingsProductsFeeToIncomeAccountMappingsIncomeAccount?

    public init(charge: GetSavingsProductsFeeToIncomeAccountMappingsCharge?, incomeAccount: GetSavingsProductsFeeToIncomeAccountMappingsIncomeAccount?) {
        self.charge = charge
        self.incomeAccount = incomeAccount
    }


}

