//
// GetSelfBeneficiariesTPTTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfBeneficiariesTPTTemplateResponse: Codable {

    public var accountTypeOptions: [GetSelfBeneficiariesAccountOptions]?

    public init(accountTypeOptions: [GetSelfBeneficiariesAccountOptions]?) {
        self.accountTypeOptions = accountTypeOptions
    }


}

