//
// GetSelfClientsClientIdTransactionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfClientsClientIdTransactionsResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetSelfClientsClientIdTransactionsPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetSelfClientsClientIdTransactionsPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

