//
// GetSelfLoansLoanIdTransactionsTransactionIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfLoansLoanIdTransactionsTransactionIdResponse: Codable {

    public var _id: Int?
    public var type: GetSelfLoansLoanIdTransactionsType?
    public var date: Date?
    public var manuallyReversed: Bool?
    public var currency: GetLoanCurrency?
    public var amount: Float?
    public var interestPortion: Float?

    public init(_id: Int?, type: GetSelfLoansLoanIdTransactionsType?, date: Date?, manuallyReversed: Bool?, currency: GetLoanCurrency?, amount: Float?, interestPortion: Float?) {
        self._id = _id
        self.type = type
        self.date = date
        self.manuallyReversed = manuallyReversed
        self.currency = currency
        self.amount = amount
        self.interestPortion = interestPortion
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case date
        case manuallyReversed
        case currency
        case amount
        case interestPortion
    }


}

