//
// GetSelfClientsChargesPageItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfClientsChargesPageItems: Codable {

    public var _id: Int?
    public var clientId: Int?
    public var chargeId: Int?
    public var name: String?
    public var chargeTimeType: GetSelfClientsChargeTimeType?
    public var dueDate: Date?
    public var chargeCalculationType: GetSelfClientsChargeCalculationType?
    public var currency: GetSelfClientsSavingsAccountsCurrency?
    public var amount: Float?
    public var amountPaid: Float?
    public var amountWaived: Float?
    public var amountWrittenOff: Float?
    public var amountOutstanding: Float?
    public var penalty: Bool?
    public var isActive: Bool?
    public var isPaid: Bool?
    public var isWaived: Bool?

    public init(_id: Int?, clientId: Int?, chargeId: Int?, name: String?, chargeTimeType: GetSelfClientsChargeTimeType?, dueDate: Date?, chargeCalculationType: GetSelfClientsChargeCalculationType?, currency: GetSelfClientsSavingsAccountsCurrency?, amount: Float?, amountPaid: Float?, amountWaived: Float?, amountWrittenOff: Float?, amountOutstanding: Float?, penalty: Bool?, isActive: Bool?, isPaid: Bool?, isWaived: Bool?) {
        self._id = _id
        self.clientId = clientId
        self.chargeId = chargeId
        self.name = name
        self.chargeTimeType = chargeTimeType
        self.dueDate = dueDate
        self.chargeCalculationType = chargeCalculationType
        self.currency = currency
        self.amount = amount
        self.amountPaid = amountPaid
        self.amountWaived = amountWaived
        self.amountWrittenOff = amountWrittenOff
        self.amountOutstanding = amountOutstanding
        self.penalty = penalty
        self.isActive = isActive
        self.isPaid = isPaid
        self.isWaived = isWaived
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case clientId
        case chargeId
        case name
        case chargeTimeType
        case dueDate
        case chargeCalculationType
        case currency
        case amount
        case amountPaid
        case amountWaived
        case amountWrittenOff
        case amountOutstanding
        case penalty
        case isActive
        case isPaid
        case isWaived
    }


}

