//
// GetSavingsAccountsTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsAccountsTemplateResponse: Codable {

    public var clientId: Int?
    public var clientName: String?
    public var productOptions: [GetSavingsProductOptions]?

    public init(clientId: Int?, clientName: String?, productOptions: [GetSavingsProductOptions]?) {
        self.clientId = clientId
        self.clientName = clientName
        self.productOptions = productOptions
    }


}

