//
// GetSelfClientsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfClientsResponse: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [GetSelfClientsPageItems]?

    public init(totalFilteredRecords: Int?, pageItems: [GetSelfClientsPageItems]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

