//
// GetStandingInstructionHistoryToClient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetStandingInstructionHistoryToClient: Codable {

    public var _id: Int64?
    public var displayName: String?
    public var officeId: Int64?
    public var officeName: String?

    public init(_id: Int64?, displayName: String?, officeId: Int64?, officeName: String?) {
        self._id = _id
        self.displayName = displayName
        self.officeId = officeId
        self.officeName = officeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case officeId
        case officeName
    }


}

