//
// GetSelfLoansTimeline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfLoansTimeline: Codable {

    public var expectedDisbursementDate: Date?

    public init(expectedDisbursementDate: Date?) {
        self.expectedDisbursementDate = expectedDisbursementDate
    }


}

