//
// GetSelfSavingsTransactionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfSavingsTransactionType: Codable {

    public var _id: Int?
    public var code: String?
    public var value: String?
    public var deposit: Bool?
    public var withdrawal: Bool?
    public var interestPosting: Bool?
    public var feeDeduction: Bool?

    public init(_id: Int?, code: String?, value: String?, deposit: Bool?, withdrawal: Bool?, interestPosting: Bool?, feeDeduction: Bool?) {
        self._id = _id
        self.code = code
        self.value = value
        self.deposit = deposit
        self.withdrawal = withdrawal
        self.interestPosting = interestPosting
        self.feeDeduction = feeDeduction
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case value
        case deposit
        case withdrawal
        case interestPosting
        case feeDeduction
    }


}

