//
// GetSavingsAccountsSavingsAccountIdChargesTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsAccountsSavingsAccountIdChargesTemplateResponse: Codable {

    public var amountPaid: Float?
    public var amountWaived: Float?
    public var amountWrittenOff: Float?
    public var chargeOptions: [GetSavingsChargesOptions]?
    public var penalty: Bool?

    public init(amountPaid: Float?, amountWaived: Float?, amountWrittenOff: Float?, chargeOptions: [GetSavingsChargesOptions]?, penalty: Bool?) {
        self.amountPaid = amountPaid
        self.amountWaived = amountWaived
        self.amountWrittenOff = amountWrittenOff
        self.chargeOptions = chargeOptions
        self.penalty = penalty
    }


}

