//
// GetSelfClientsClientIdAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSelfClientsClientIdAccountsResponse: Codable {

    public var loanAccounts: [GetSelfClientsLoanAccounts]?
    public var savingsAccounts: [GetSelfClientsSavingsAccounts]?

    public init(loanAccounts: [GetSelfClientsLoanAccounts]?, savingsAccounts: [GetSelfClientsSavingsAccounts]?) {
        self.loanAccounts = loanAccounts
        self.savingsAccounts = savingsAccounts
    }


}

