//
// GetSavingsAccountsAccountIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsAccountsAccountIdResponse: Codable {

    public var _id: Int?
    public var accountNo: String?
    public var clientId: Int?
    public var clientName: String?
    public var savingsProductId: Int?
    public var savingsProductName: String?
    public var fieldOfficerId: Int?
    public var status: GetSavingsStatus?
    public var timeline: GetSavingsTimeline?
    public var currency: GetSavingsCurrency?
    public var nominalAnnualInterestRate: Double?
    public var interestCompoundingPeriodType: GetSavingsInterestCompoundingPeriodType?
    public var interestPostingPeriodType: GetSavingsInterestPostingPeriodType?
    public var interestCalculationType: GetSavingsInterestCalculationType?
    public var interestCalculationDaysInYearType: GetSavingsInterestCalculationDaysInYearType?
    public var summary: GetSavingsAccountsSummary?

    public init(_id: Int?, accountNo: String?, clientId: Int?, clientName: String?, savingsProductId: Int?, savingsProductName: String?, fieldOfficerId: Int?, status: GetSavingsStatus?, timeline: GetSavingsTimeline?, currency: GetSavingsCurrency?, nominalAnnualInterestRate: Double?, interestCompoundingPeriodType: GetSavingsInterestCompoundingPeriodType?, interestPostingPeriodType: GetSavingsInterestPostingPeriodType?, interestCalculationType: GetSavingsInterestCalculationType?, interestCalculationDaysInYearType: GetSavingsInterestCalculationDaysInYearType?, summary: GetSavingsAccountsSummary?) {
        self._id = _id
        self.accountNo = accountNo
        self.clientId = clientId
        self.clientName = clientName
        self.savingsProductId = savingsProductId
        self.savingsProductName = savingsProductName
        self.fieldOfficerId = fieldOfficerId
        self.status = status
        self.timeline = timeline
        self.currency = currency
        self.nominalAnnualInterestRate = nominalAnnualInterestRate
        self.interestCompoundingPeriodType = interestCompoundingPeriodType
        self.interestPostingPeriodType = interestPostingPeriodType
        self.interestCalculationType = interestCalculationType
        self.interestCalculationDaysInYearType = interestCalculationDaysInYearType
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountNo
        case clientId
        case clientName
        case savingsProductId
        case savingsProductName
        case fieldOfficerId
        case status
        case timeline
        case currency
        case nominalAnnualInterestRate
        case interestCompoundingPeriodType
        case interestPostingPeriodType
        case interestCalculationType
        case interestCalculationDaysInYearType
        case summary
    }


}

