//
// GetSavingsTimeline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSavingsTimeline: Codable {

    public var submittedOnDate: Date?

    public init(submittedOnDate: Date?) {
        self.submittedOnDate = submittedOnDate
    }


}

