//
// GetTaxesGroupResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetTaxesGroupResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var taxAssociations: [GetTaxesGroupTaxAssociations]?

    public init(_id: Int?, name: String?, taxAssociations: [GetTaxesGroupTaxAssociations]?) {
        self._id = _id
        self.name = name
        self.taxAssociations = taxAssociations
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case taxAssociations
    }


}

