//
// GetTellersTellerIdCashiersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetTellersTellerIdCashiersResponse: Codable {

    public var tellerId: Int64?
    public var tellerName: String?
    public var officeId: Int64?
    public var officeName: String?
    public var cashiers: [CashierData]?

    public init(tellerId: Int64?, tellerName: String?, officeId: Int64?, officeName: String?, cashiers: [CashierData]?) {
        self.tellerId = tellerId
        self.tellerName = tellerName
        self.officeId = officeId
        self.officeName = officeName
        self.cashiers = cashiers
    }


}

