//
// GetTemplatesTemplateIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetTemplatesTemplateIdResponse: Codable {

    public var _id: Int64?
    public var name: String?
    public var entity: Int64?
    public var type: Int64?
    public var text: String?
    public var mappers: [TemplateMapper]?

    public init(_id: Int64?, name: String?, entity: Int64?, type: Int64?, text: String?, mappers: [TemplateMapper]?) {
        self._id = _id
        self.name = name
        self.entity = entity
        self.type = type
        self.text = text
        self.mappers = mappers
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case entity
        case type
        case text
        case mappers
    }


}

