//
// GetTaxesComponentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetTaxesComponentsResponse: Codable {

    public var _id: Int?
    public var name: String?
    public var percentage: Float?
    public var creditAccountType: GetTaxesComponentsCreditAccountType?
    public var creditAccount: GetTaxesComponentsCreditAccount?
    public var startDate: Date?
    public var taxComponentsHistories: [GetTaxesComponentsHistories]?

    public init(_id: Int?, name: String?, percentage: Float?, creditAccountType: GetTaxesComponentsCreditAccountType?, creditAccount: GetTaxesComponentsCreditAccount?, startDate: Date?, taxComponentsHistories: [GetTaxesComponentsHistories]?) {
        self._id = _id
        self.name = name
        self.percentage = percentage
        self.creditAccountType = creditAccountType
        self.creditAccount = creditAccount
        self.startDate = startDate
        self.taxComponentsHistories = taxComponentsHistories
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case percentage
        case creditAccountType
        case creditAccount
        case startDate
        case taxComponentsHistories
    }


}

