//
// GetUsersTemplateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUsersTemplateResponse: Codable {

    public var allowedOffices: [OfficeData]?
    public var availableRoles: [RoleData]?

    public init(allowedOffices: [OfficeData]?, availableRoles: [RoleData]?) {
        self.allowedOffices = allowedOffices
        self.availableRoles = availableRoles
    }


}

