//
// GetUserDetailsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserDetailsResponse: Codable {

    public var username: String?
    public var userId: Int64?
    public var accessToken: String?
    public var authenticated: Bool?
    public var officeId: Int64?
    public var officeName: String?
    public var staffId: Int64?
    public var staffDisplayName: String?
    public var organisationalRole: EnumOptionData?
    public var roles: [RoleData]?
    public var permissions: [String]?

    public init(username: String?, userId: Int64?, accessToken: String?, authenticated: Bool?, officeId: Int64?, officeName: String?, staffId: Int64?, staffDisplayName: String?, organisationalRole: EnumOptionData?, roles: [RoleData]?, permissions: [String]?) {
        self.username = username
        self.userId = userId
        self.accessToken = accessToken
        self.authenticated = authenticated
        self.officeId = officeId
        self.officeName = officeName
        self.staffId = staffId
        self.staffDisplayName = staffDisplayName
        self.organisationalRole = organisationalRole
        self.roles = roles
        self.permissions = permissions
    }


}

