//
// GetUsersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUsersResponse: Codable {

    public var _id: Int64?
    public var username: String?
    public var officeId: Int64?
    public var officeName: String?
    public var firstname: String?
    public var lastname: String?
    public var email: String?
    public var passwordNeverExpires: Bool?
    public var staff: StaffData?
    public var selectedRoles: [RoleData]?

    public init(_id: Int64?, username: String?, officeId: Int64?, officeName: String?, firstname: String?, lastname: String?, email: String?, passwordNeverExpires: Bool?, staff: StaffData?, selectedRoles: [RoleData]?) {
        self._id = _id
        self.username = username
        self.officeId = officeId
        self.officeName = officeName
        self.firstname = firstname
        self.lastname = lastname
        self.email = email
        self.passwordNeverExpires = passwordNeverExpires
        self.staff = staff
        self.selectedRoles = selectedRoles
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case officeId
        case officeName
        case firstname
        case lastname
        case email
        case passwordNeverExpires
        case staff
        case selectedRoles
    }


}

