//
// HookTemplateData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HookTemplateData: Codable {

    public var serviceId: Int64?

    public init(serviceId: Int64?) {
        self.serviceId = serviceId
    }


}

