//
// JobDetailHistoryDataSwagger.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JobDetailHistoryDataSwagger: Codable {

    public var version: Int64?
    public var jobRunStartTime: Date?
    public var jobRunEndTime: Date?
    public var status: String?
    public var triggerType: String?

    public init(version: Int64?, jobRunStartTime: Date?, jobRunEndTime: Date?, status: String?, triggerType: String?) {
        self.version = version
        self.jobRunStartTime = jobRunStartTime
        self.jobRunEndTime = jobRunEndTime
        self.status = status
        self.triggerType = triggerType
    }


}

