//
// JournalEntryData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JournalEntryData: Codable {

    public var _id: Int64?
    public var officeId: Int64?
    public var glAccountId: Int64?
    public var glAccountType: EnumOptionData?
    public var transactionDate: Date?
    public var entryType: EnumOptionData?
    public var amount: Double?
    public var transactionId: String?
    public var rowIndex: Int?

    public init(_id: Int64?, officeId: Int64?, glAccountId: Int64?, glAccountType: EnumOptionData?, transactionDate: Date?, entryType: EnumOptionData?, amount: Double?, transactionId: String?, rowIndex: Int?) {
        self._id = _id
        self.officeId = officeId
        self.glAccountId = glAccountId
        self.glAccountType = glAccountType
        self.transactionDate = transactionDate
        self.entryType = entryType
        self.amount = amount
        self.transactionId = transactionId
        self.rowIndex = rowIndex
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case officeId
        case glAccountId
        case glAccountType
        case transactionDate
        case entryType
        case amount
        case transactionId
        case rowIndex
    }


}

