//
// LoanProductGuaranteeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanProductGuaranteeDetails: Codable {

    public var _id: Int64?
    public var mandatoryGuarantee: Double?
    public var minimumGuaranteeFromOwnFunds: Double?
    public var minimumGuaranteeFromGuarantor: Double?
    public var new: Bool?

    public init(_id: Int64?, mandatoryGuarantee: Double?, minimumGuaranteeFromOwnFunds: Double?, minimumGuaranteeFromGuarantor: Double?, new: Bool?) {
        self._id = _id
        self.mandatoryGuarantee = mandatoryGuarantee
        self.minimumGuaranteeFromOwnFunds = minimumGuaranteeFromOwnFunds
        self.minimumGuaranteeFromGuarantor = minimumGuaranteeFromGuarantor
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case mandatoryGuarantee
        case minimumGuaranteeFromOwnFunds
        case minimumGuaranteeFromGuarantor
        case new
    }


}

