//
// LoanProductInterestRecalculationDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanProductInterestRecalculationDetails: Codable {

    public enum RestFrequencyType: String, Codable { 
        case invalid = "INVALID"
        case sameAsRepaymentPeriod = "SAME_AS_REPAYMENT_PERIOD"
        case daily = "DAILY"
        case weekly = "WEEKLY"
        case monthly = "MONTHLY"
    }
    public enum CompoundingFrequencyType: String, Codable { 
        case invalid = "INVALID"
        case sameAsRepaymentPeriod = "SAME_AS_REPAYMENT_PERIOD"
        case daily = "DAILY"
        case weekly = "WEEKLY"
        case monthly = "MONTHLY"
    }
    public var _id: Int64?
    public var interestRecalculationCompoundingMethod: Int?
    public var rescheduleStrategyMethod: Int?
    public var restFrequencyType: RestFrequencyType?
    public var restInterval: Int?
    public var restFrequencyNthDay: Int?
    public var restFrequencyWeekday: Int?
    public var restFrequencyOnDay: Int?
    public var compoundingFrequencyType: CompoundingFrequencyType?
    public var compoundingInterval: Int?
    public var compoundingFrequencyNthDay: Int?
    public var compoundingFrequencyWeekday: Int?
    public var compoundingFrequencyOnDay: Int?
    public var isCompoundingToBePostedAsTransaction: Bool?
    public var arrearsBasedOnOriginalSchedule: Bool?
    public var new: Bool?

    public init(_id: Int64?, interestRecalculationCompoundingMethod: Int?, rescheduleStrategyMethod: Int?, restFrequencyType: RestFrequencyType?, restInterval: Int?, restFrequencyNthDay: Int?, restFrequencyWeekday: Int?, restFrequencyOnDay: Int?, compoundingFrequencyType: CompoundingFrequencyType?, compoundingInterval: Int?, compoundingFrequencyNthDay: Int?, compoundingFrequencyWeekday: Int?, compoundingFrequencyOnDay: Int?, isCompoundingToBePostedAsTransaction: Bool?, arrearsBasedOnOriginalSchedule: Bool?, new: Bool?) {
        self._id = _id
        self.interestRecalculationCompoundingMethod = interestRecalculationCompoundingMethod
        self.rescheduleStrategyMethod = rescheduleStrategyMethod
        self.restFrequencyType = restFrequencyType
        self.restInterval = restInterval
        self.restFrequencyNthDay = restFrequencyNthDay
        self.restFrequencyWeekday = restFrequencyWeekday
        self.restFrequencyOnDay = restFrequencyOnDay
        self.compoundingFrequencyType = compoundingFrequencyType
        self.compoundingInterval = compoundingInterval
        self.compoundingFrequencyNthDay = compoundingFrequencyNthDay
        self.compoundingFrequencyWeekday = compoundingFrequencyWeekday
        self.compoundingFrequencyOnDay = compoundingFrequencyOnDay
        self.isCompoundingToBePostedAsTransaction = isCompoundingToBePostedAsTransaction
        self.arrearsBasedOnOriginalSchedule = arrearsBasedOnOriginalSchedule
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case interestRecalculationCompoundingMethod
        case rescheduleStrategyMethod
        case restFrequencyType
        case restInterval
        case restFrequencyNthDay
        case restFrequencyWeekday
        case restFrequencyOnDay
        case compoundingFrequencyType
        case compoundingInterval
        case compoundingFrequencyNthDay
        case compoundingFrequencyWeekday
        case compoundingFrequencyOnDay
        case isCompoundingToBePostedAsTransaction
        case arrearsBasedOnOriginalSchedule
        case new
    }


}

