//
// LoanTransactionProcessingStrategy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanTransactionProcessingStrategy: Codable {

    public var _id: Int64?
    public var standardStrategy: Bool?
    public var heavensfamilyStrategy: Bool?
    public var earlyPaymentStrategy: Bool?
    public var creocoreStrategy: Bool?
    public var indianRBIStrategy: Bool?
    public var principalInterestPenaltiesFeesOrderStrategy: Bool?
    public var interestPrincipalPenaltiesFeesOrderStrategy: Bool?
    public var new: Bool?

    public init(_id: Int64?, standardStrategy: Bool?, heavensfamilyStrategy: Bool?, earlyPaymentStrategy: Bool?, creocoreStrategy: Bool?, indianRBIStrategy: Bool?, principalInterestPenaltiesFeesOrderStrategy: Bool?, interestPrincipalPenaltiesFeesOrderStrategy: Bool?, new: Bool?) {
        self._id = _id
        self.standardStrategy = standardStrategy
        self.heavensfamilyStrategy = heavensfamilyStrategy
        self.earlyPaymentStrategy = earlyPaymentStrategy
        self.creocoreStrategy = creocoreStrategy
        self.indianRBIStrategy = indianRBIStrategy
        self.principalInterestPenaltiesFeesOrderStrategy = principalInterestPenaltiesFeesOrderStrategy
        self.interestPrincipalPenaltiesFeesOrderStrategy = interestPrincipalPenaltiesFeesOrderStrategy
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case standardStrategy
        case heavensfamilyStrategy
        case earlyPaymentStrategy
        case creocoreStrategy
        case indianRBIStrategy
        case principalInterestPenaltiesFeesOrderStrategy
        case interestPrincipalPenaltiesFeesOrderStrategy
        case new
    }


}

