//
// Money.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Money: Codable {

    public var currencyCode: String?
    public var currencyDigitsAfterDecimal: Int?
    public var amount: Double?
    public var currency: MonetaryCurrency?
    public var zero: Bool?
    public var greaterThanZero: Bool?
    public var lessThanZero: Bool?
    public var amountDefaultedToNullIfZero: Double?
    public var currencyInMultiplesOf: Int?

    public init(currencyCode: String?, currencyDigitsAfterDecimal: Int?, amount: Double?, currency: MonetaryCurrency?, zero: Bool?, greaterThanZero: Bool?, lessThanZero: Bool?, amountDefaultedToNullIfZero: Double?, currencyInMultiplesOf: Int?) {
        self.currencyCode = currencyCode
        self.currencyDigitsAfterDecimal = currencyDigitsAfterDecimal
        self.amount = amount
        self.currency = currency
        self.zero = zero
        self.greaterThanZero = greaterThanZero
        self.lessThanZero = lessThanZero
        self.amountDefaultedToNullIfZero = amountDefaultedToNullIfZero
        self.currencyInMultiplesOf = currencyInMultiplesOf
    }


}

