//
// MonthDay.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MonthDay: Codable {

    public var dayOfMonth: Int?
    public var monthOfYear: Int?
    public var fieldTypes: [DateTimeFieldType]?
    public var chronology: Chronology?
    public var values: [Int]?
    public var fields: [DateTimeField]?

    public init(dayOfMonth: Int?, monthOfYear: Int?, fieldTypes: [DateTimeFieldType]?, chronology: Chronology?, values: [Int]?, fields: [DateTimeField]?) {
        self.dayOfMonth = dayOfMonth
        self.monthOfYear = monthOfYear
        self.fieldTypes = fieldTypes
        self.chronology = chronology
        self.values = values
        self.fields = fields
    }


}

