//
// OfficeData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OfficeData: Codable {

    public var _id: Int64?
    public var openingDate: Date?
    public var hierarchy: String?
    public var rowIndex: Int?

    public init(_id: Int64?, openingDate: Date?, hierarchy: String?, rowIndex: Int?) {
        self._id = _id
        self.openingDate = openingDate
        self.hierarchy = hierarchy
        self.rowIndex = rowIndex
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case openingDate
        case hierarchy
        case rowIndex
    }


}

