//
// Page.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Page: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [Any]?

    public init(totalFilteredRecords: Int?, pageItems: [Any]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

