//
// PageCashierTransactionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageCashierTransactionData: Codable {

    public var totalFilteredRecords: Int?
    public var pageItems: [CashierTransactionData]?

    public init(totalFilteredRecords: Int?, pageItems: [CashierTransactionData]?) {
        self.totalFilteredRecords = totalFilteredRecords
        self.pageItems = pageItems
    }


}

