//
// Permission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Permission: Codable {

    public var _id: Int64?
    public var grouping: String?
    public var code: String?
    public var new: Bool?

    public init(_id: Int64?, grouping: String?, code: String?, new: Bool?) {
        self._id = _id
        self.grouping = grouping
        self.code = code
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case grouping
        case code
        case new
    }


}

