//
// PostTellersTellerIdCashiersRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostTellersTellerIdCashiersRequest: Codable {

    public var endDate: Date?
    public var _description: String?
    public var isFullDay: Bool?
    public var staffId: Int64?
    public var locale: String?
    public var dateFormat: String?
    public var startDate: Date?

    public init(endDate: Date?, _description: String?, isFullDay: Bool?, staffId: Int64?, locale: String?, dateFormat: String?, startDate: Date?) {
        self.endDate = endDate
        self._description = _description
        self.isFullDay = isFullDay
        self.staffId = staffId
        self.locale = locale
        self.dateFormat = dateFormat
        self.startDate = startDate
    }

    public enum CodingKeys: String, CodingKey { 
        case endDate
        case _description = "description"
        case isFullDay
        case staffId
        case locale
        case dateFormat
        case startDate
    }


}

