//
// PostDataTablesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostDataTablesResponse: Codable {

    public var resourceIdentifier: String?

    public init(resourceIdentifier: String?) {
        self.resourceIdentifier = resourceIdentifier
    }


}

