//
// PostPaymentTypesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostPaymentTypesRequest: Codable {

    public var name: String?
    public var _description: String?
    public var isCashPayment: Bool?
    public var position: Int?

    public init(name: String?, _description: String?, isCashPayment: Bool?, position: Int?) {
        self.name = name
        self._description = _description
        self.isCashPayment = isCashPayment
        self.position = position
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case isCashPayment
        case position
    }


}

