//
// PostRepostRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostRepostRequest: Codable {

    public var reportName: String?
    public var reportType: String?
    public var reportSubType: String?
    public var reportCategory: String?
    public var _description: String?
    public var reportSql: String?
    public var reportParameters: [ReportParameterData]?

    public init(reportName: String?, reportType: String?, reportSubType: String?, reportCategory: String?, _description: String?, reportSql: String?, reportParameters: [ReportParameterData]?) {
        self.reportName = reportName
        self.reportType = reportType
        self.reportSubType = reportSubType
        self.reportCategory = reportCategory
        self._description = _description
        self.reportSql = reportSql
        self.reportParameters = reportParameters
    }

    public enum CodingKeys: String, CodingKey { 
        case reportName
        case reportType
        case reportSubType
        case reportCategory
        case _description = "description"
        case reportSql
        case reportParameters
    }


}

