//
// PostLoansLoanIdChargesChargeIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostLoansLoanIdChargesChargeIdRequest: Codable {

    public var dateFormat: String?
    public var locale: String?
    public var transactionDate: String?

    public init(dateFormat: String?, locale: String?, transactionDate: String?) {
        self.dateFormat = dateFormat
        self.locale = locale
        self.transactionDate = transactionDate
    }


}

