//
// PostGLCLosuresRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostGLCLosuresRequest: Codable {

    public var officeId: Int64?
    public var closingDate: Date?
    public var comments: String?
    public var locale: String?
    public var dateFormat: String?

    public init(officeId: Int64?, closingDate: Date?, comments: String?, locale: String?, dateFormat: String?) {
        self.officeId = officeId
        self.closingDate = closingDate
        self.comments = comments
        self.locale = locale
        self.dateFormat = dateFormat
    }


}

