//
// PostGroupsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostGroupsRequest: Codable {

    public var officeId: Int?
    public var name: String?
    public var active: Bool?

    public init(officeId: Int?, name: String?, active: Bool?) {
        self.officeId = officeId
        self.name = name
        self.active = active
    }


}

