//
// PostJournalEntriesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostJournalEntriesResponse: Codable {

    /** 1 */
    public var officeId: Int64?
    /** RS9MCISID4WK1ZM */
    public var transactionId: String?

    public init(officeId: Int64?, transactionId: String?) {
        self.officeId = officeId
        self.transactionId = transactionId
    }


}

