//
// PostDataTablesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostDataTablesRequest: Codable {

    public var applicationTableName: String?
    public var registeredTableName: String?
    public var multiRow: Bool?
    public var columnHeaderData: [ResultsetColumnHeaderData]?

    public init(applicationTableName: String?, registeredTableName: String?, multiRow: Bool?, columnHeaderData: [ResultsetColumnHeaderData]?) {
        self.applicationTableName = applicationTableName
        self.registeredTableName = registeredTableName
        self.multiRow = multiRow
        self.columnHeaderData = columnHeaderData
    }


}

