//
// PostClientsClientIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostClientsClientIdResponse: Codable {

    public var clientId: Int?
    public var resourceId: Int?

    public init(clientId: Int?, resourceId: Int?) {
        self.clientId = clientId
        self.resourceId = resourceId
    }


}

