//
// PostGroupsGroupIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostGroupsGroupIdRequest: Codable {

    public var destinationGroupId: Int?
    public var clients: [PostGroupsGroupIdClients]?

    public init(destinationGroupId: Int?, clients: [PostGroupsGroupIdClients]?) {
        self.destinationGroupId = destinationGroupId
        self.clients = clients
    }


}

