//
// PostSelfLoansLoanIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostSelfLoansLoanIdResponse: Codable {

    public var officeId: Int?
    public var clientId: Int?
    public var loanId: Int?
    public var resourceId: Int?
    public var changes: PostSelfLoansLoanIdChanges?

    public init(officeId: Int?, clientId: Int?, loanId: Int?, resourceId: Int?, changes: PostSelfLoansLoanIdChanges?) {
        self.officeId = officeId
        self.clientId = clientId
        self.loanId = loanId
        self.resourceId = resourceId
        self.changes = changes
    }


}

