//
// PostFixedDepositProductsChartSlabs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostFixedDepositProductsChartSlabs: Codable {

    public var _description: String?
    public var periodType: Int?
    public var fromPeriod: Int?
    public var toPeriod: Int?
    public var annualInterestRate: Double?

    public init(_description: String?, periodType: Int?, fromPeriod: Int?, toPeriod: Int?, annualInterestRate: Double?) {
        self._description = _description
        self.periodType = periodType
        self.fromPeriod = fromPeriod
        self.toPeriod = toPeriod
        self.annualInterestRate = annualInterestRate
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case periodType
        case fromPeriod
        case toPeriod
        case annualInterestRate
    }


}

