//
// PostAccountsTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostAccountsTypeResponse: Codable {

    public var resourceId: Int?

    public init(resourceId: Int?) {
        self.resourceId = resourceId
    }


}

