//
// PostEntityDatatableChecksTemplateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostEntityDatatableChecksTemplateRequest: Codable {

    public var entity: String?
    public var status: Int64?
    public var datatableName: String?
    public var productId: Int64?

    public init(entity: String?, status: Int64?, datatableName: String?, productId: Int64?) {
        self.entity = entity
        self.status = status
        self.datatableName = datatableName
        self.productId = productId
    }


}

