//
// PostInterestRateChartsChartIdChartSlabsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostInterestRateChartsChartIdChartSlabsRequest: Codable {

    public var periodType: Int?
    public var fromPeriod: Int?
    public var toPeriod: Int?
    public var annualInterestRate: Double?
    public var _description: String?
    public var locale: String?
    public var incentives: [PostInterestRateChartsChartIdChartSlabsIncentives]?

    public init(periodType: Int?, fromPeriod: Int?, toPeriod: Int?, annualInterestRate: Double?, _description: String?, locale: String?, incentives: [PostInterestRateChartsChartIdChartSlabsIncentives]?) {
        self.periodType = periodType
        self.fromPeriod = fromPeriod
        self.toPeriod = toPeriod
        self.annualInterestRate = annualInterestRate
        self._description = _description
        self.locale = locale
        self.incentives = incentives
    }

    public enum CodingKeys: String, CodingKey { 
        case periodType
        case fromPeriod
        case toPeriod
        case annualInterestRate
        case _description = "description"
        case locale
        case incentives
    }


}

