//
// PostTellersTellerIdCashiersCashierIdSettleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostTellersTellerIdCashiersCashierIdSettleResponse: Codable {

    public var resourceId: Int64?
    public var subResourceId: Int64?

    public init(resourceId: Int64?, subResourceId: Int64?) {
        self.resourceId = resourceId
        self.subResourceId = subResourceId
    }


}

