//
// PostStandingInstructionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostStandingInstructionsRequest: Codable {

    public var fromOfficeId: Int64?
    public var fromClientId: Int64?
    public var fromAccountType: Int?
    public var name: String?
    public var transferType: Int?
    public var priority: Int?
    public var status: Int?
    public var fromAccountId: Int64?
    public var toOfficeId: Int64?
    public var toClientId: Int64?
    public var toAccountType: Int?
    public var toAccountId: Int64?
    public var instructionType: Int?
    public var amount: Int?
    public var validFrom: String?
    public var recurrenceType: Int?
    public var recurrenceInterval: Int?
    public var recurrenceFrequency: Int?
    /** en */
    public var locale: String?
    public var dateFormat: String?
    public var recurrenceOnMonthDay: String?
    public var monthDayFormat: String?

    public init(fromOfficeId: Int64?, fromClientId: Int64?, fromAccountType: Int?, name: String?, transferType: Int?, priority: Int?, status: Int?, fromAccountId: Int64?, toOfficeId: Int64?, toClientId: Int64?, toAccountType: Int?, toAccountId: Int64?, instructionType: Int?, amount: Int?, validFrom: String?, recurrenceType: Int?, recurrenceInterval: Int?, recurrenceFrequency: Int?, locale: String?, dateFormat: String?, recurrenceOnMonthDay: String?, monthDayFormat: String?) {
        self.fromOfficeId = fromOfficeId
        self.fromClientId = fromClientId
        self.fromAccountType = fromAccountType
        self.name = name
        self.transferType = transferType
        self.priority = priority
        self.status = status
        self.fromAccountId = fromAccountId
        self.toOfficeId = toOfficeId
        self.toClientId = toClientId
        self.toAccountType = toAccountType
        self.toAccountId = toAccountId
        self.instructionType = instructionType
        self.amount = amount
        self.validFrom = validFrom
        self.recurrenceType = recurrenceType
        self.recurrenceInterval = recurrenceInterval
        self.recurrenceFrequency = recurrenceFrequency
        self.locale = locale
        self.dateFormat = dateFormat
        self.recurrenceOnMonthDay = recurrenceOnMonthDay
        self.monthDayFormat = monthDayFormat
    }


}

