//
// PostClientsClientIdChargesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostClientsClientIdChargesResponse: Codable {

    public var officeId: Int?
    public var chargeId: Int?
    public var resourceId: Int?

    public init(officeId: Int?, chargeId: Int?, resourceId: Int?) {
        self.officeId = officeId
        self.chargeId = chargeId
        self.resourceId = resourceId
    }


}

