//
// PostLoansLoanIdScheduleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostLoansLoanIdScheduleResponse: Codable {

    public var loanId: Int?
    public var changes: PostLoanChanges?

    public init(loanId: Int?, changes: PostLoanChanges?) {
        self.loanId = loanId
        self.changes = changes
    }


}

