//
// PostSurveySurveyNameApptableIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostSurveySurveyNameApptableIdResponse: Codable {

    public var officeId: Int64?
    public var clientId: Int64?
    public var resourceId: Int64?

    public init(officeId: Int64?, clientId: Int64?, resourceId: Int64?) {
        self.officeId = officeId
        self.clientId = clientId
        self.resourceId = resourceId
    }


}

