//
// PostAccountsCharges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostAccountsCharges: Codable {

    public var chargeId: Int?
    public var amount: Int?

    public init(chargeId: Int?, amount: Int?) {
        self.chargeId = chargeId
        self.amount = amount
    }


}

