//
// PostAccountsTypeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostAccountsTypeRequest: Codable {

    public var clientId: Int?
    public var productId: Int?
    public var requestedShares: Int?
    public var externalId: Int?
    public var submittedDate: String?
    public var minimumActivePeriod: Int?
    public var minimumActivePeriodFrequencyType: Int?
    public var lockinPeriodFrequency: Int?
    public var lockinPeriodFrequencyType: Int?
    public var applicationDate: String?
    public var allowDividendCalculationForInactiveClients: Bool?
    public var locale: String?
    public var dateFormat: String?
    public var charges: [PostAccountsCharges]?
    public var savingsAccountId: Int?

    public init(clientId: Int?, productId: Int?, requestedShares: Int?, externalId: Int?, submittedDate: String?, minimumActivePeriod: Int?, minimumActivePeriodFrequencyType: Int?, lockinPeriodFrequency: Int?, lockinPeriodFrequencyType: Int?, applicationDate: String?, allowDividendCalculationForInactiveClients: Bool?, locale: String?, dateFormat: String?, charges: [PostAccountsCharges]?, savingsAccountId: Int?) {
        self.clientId = clientId
        self.productId = productId
        self.requestedShares = requestedShares
        self.externalId = externalId
        self.submittedDate = submittedDate
        self.minimumActivePeriod = minimumActivePeriod
        self.minimumActivePeriodFrequencyType = minimumActivePeriodFrequencyType
        self.lockinPeriodFrequency = lockinPeriodFrequency
        self.lockinPeriodFrequencyType = lockinPeriodFrequencyType
        self.applicationDate = applicationDate
        self.allowDividendCalculationForInactiveClients = allowDividendCalculationForInactiveClients
        self.locale = locale
        self.dateFormat = dateFormat
        self.charges = charges
        self.savingsAccountId = savingsAccountId
    }


}

