//
// PostSavingsAccountsSavingsAccountIdChargesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostSavingsAccountsSavingsAccountIdChargesRequest: Codable {

    public var chargeId: Int?
    public var locale: String?
    public var amount: Float?
    public var dateFormat: String?
    public var dueDate: String?

    public init(chargeId: Int?, locale: String?, amount: Float?, dateFormat: String?, dueDate: String?) {
        self.chargeId = chargeId
        self.locale = locale
        self.amount = amount
        self.dateFormat = dateFormat
        self.dueDate = dueDate
    }


}

