//
// PostMakerCheckersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostMakerCheckersResponse: Codable {

    public var auditId: Int64?

    public init(auditId: Int64?) {
        self.auditId = auditId
    }


}

