//
// PostClientsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostClientsRequest: Codable {

    public var officeId: Int?
    public var fullname: String?
    public var groupId: Int?
    public var dateFormat: String?
    public var locale: String?
    public var active: Bool?
    public var activationDate: String?

    public init(officeId: Int?, fullname: String?, groupId: Int?, dateFormat: String?, locale: String?, active: Bool?, activationDate: String?) {
        self.officeId = officeId
        self.fullname = fullname
        self.groupId = groupId
        self.dateFormat = dateFormat
        self.locale = locale
        self.active = active
        self.activationDate = activationDate
    }


}

