//
// PostDataTablesAppTableIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostDataTablesAppTableIdRequest: Codable {

    public var businessDescription: String?
    public var comment: String?
    public var educationCv: String?
    public var genderCd: Int64?
    public var highestRatePaid: Double?
    public var nextVisit: String?
    public var yearsinBusiness: Int64?
    public var dateFormat: String?
    public var locale: String?

    public init(businessDescription: String?, comment: String?, educationCv: String?, genderCd: Int64?, highestRatePaid: Double?, nextVisit: String?, yearsinBusiness: Int64?, dateFormat: String?, locale: String?) {
        self.businessDescription = businessDescription
        self.comment = comment
        self.educationCv = educationCv
        self.genderCd = genderCd
        self.highestRatePaid = highestRatePaid
        self.nextVisit = nextVisit
        self.yearsinBusiness = yearsinBusiness
        self.dateFormat = dateFormat
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey { 
        case businessDescription = "BusinessDescription"
        case comment = "Comment"
        case educationCv = "Education_cv"
        case genderCd = "Gender_cd"
        case highestRatePaid = "HighestRatePaid"
        case nextVisit = "NextVisit"
        case yearsinBusiness = "YearsinBusiness"
        case dateFormat
        case locale
    }


}

