//
// PostSelfLoansLoanIdChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostSelfLoansLoanIdChanges: Codable {

    public var status: PostSelfLoansLoanIdStatus?
    public var locale: String?
    public var dateFormat: String?
    public var withdrawnOnDate: String?
    public var closedOnDate: String?

    public init(status: PostSelfLoansLoanIdStatus?, locale: String?, dateFormat: String?, withdrawnOnDate: String?, closedOnDate: String?) {
        self.status = status
        self.locale = locale
        self.dateFormat = dateFormat
        self.withdrawnOnDate = withdrawnOnDate
        self.closedOnDate = closedOnDate
    }


}

