//
// PostProductsMarketPricePeriods.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostProductsMarketPricePeriods: Codable {

    public var locale: String?
    public var dateFormat: String?
    public var fromDate: String?
    public var shareValue: Int?

    public init(locale: String?, dateFormat: String?, fromDate: String?, shareValue: Int?) {
        self.locale = locale
        self.dateFormat = dateFormat
        self.fromDate = fromDate
        self.shareValue = shareValue
    }


}

