//
// PostJournalEntriesTransactionIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostJournalEntriesTransactionIdResponse: Codable {

    /** 1 */
    public var officeId: Int64?

    public init(officeId: Int64?) {
        self.officeId = officeId
    }


}

