//
// PostHolidaysResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostHolidaysResponse: Codable {

    public var resourceId: Int64?

    public init(resourceId: Int64?) {
        self.resourceId = resourceId
    }


}

