//
// PostTaxesComponentsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostTaxesComponentsRequest: Codable {

    public var name: String?
    public var percentage: Float?
    public var creditAccountType: Int?
    public var creditAcountId: Int?
    public var locale: String?
    public var dateFormat: String?
    public var startDate: String?

    public init(name: String?, percentage: Float?, creditAccountType: Int?, creditAcountId: Int?, locale: String?, dateFormat: String?, startDate: String?) {
        self.name = name
        self.percentage = percentage
        self.creditAccountType = creditAccountType
        self.creditAcountId = creditAcountId
        self.locale = locale
        self.dateFormat = dateFormat
        self.startDate = startDate
    }


}

