//
// PutAccountsChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutAccountsChanges: Codable {

    public var dateFormat: String?
    public var applicationDate: String?
    public var requestedShares: Int?
    public var locale: String?

    public init(dateFormat: String?, applicationDate: String?, requestedShares: Int?, locale: String?) {
        self.dateFormat = dateFormat
        self.applicationDate = applicationDate
        self.requestedShares = requestedShares
        self.locale = locale
    }


}

