//
// PutAccountNumberFormatsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutAccountNumberFormatsRequest: Codable {

    public var prefixType: Int64?

    public init(prefixType: Int64?) {
        self.prefixType = prefixType
    }


}

