//
// PutAccountsTypeAccountIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutAccountsTypeAccountIdRequest: Codable {

    public var locale: String?
    public var dateFormat: String?
    public var applicationDate: String?
    public var requestedShares: Int?

    public init(locale: String?, dateFormat: String?, applicationDate: String?, requestedShares: Int?) {
        self.locale = locale
        self.dateFormat = dateFormat
        self.applicationDate = applicationDate
        self.requestedShares = requestedShares
    }


}

