//
// PutClientsClientIdIdentifiersIdentifierIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutClientsClientIdIdentifiersIdentifierIdResponse: Codable {

    public var officeId: Int?
    public var clientId: Int?
    public var resourceId: Int?
    public var changes: PutClientsClientIdIdentifiersIdentifierIdRequest?

    public init(officeId: Int?, clientId: Int?, resourceId: Int?, changes: PutClientsClientIdIdentifiersIdentifierIdRequest?) {
        self.officeId = officeId
        self.clientId = clientId
        self.resourceId = resourceId
        self.changes = changes
    }


}

