//
// PutCachesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutCachesRequest: Codable {

    public var cacheType: Int64?

    public init(cacheType: Int64?) {
        self.cacheType = cacheType
    }


}

