//
// PutClientsClientIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutClientsClientIdRequest: Codable {

    public var externalId: String?

    public init(externalId: String?) {
        self.externalId = externalId
    }


}

