//
// PutCodesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutCodesResponse: Codable {

    public var resourceId: Int64?
    public var changes: PutCodesApichangesSwagger?

    public init(resourceId: Int64?, changes: PutCodesApichangesSwagger?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

