//
// PutCodeValueDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutCodeValueDataResponse: Codable {

    public var resourceId: Int64?
    public var changes: PutCodeValuechangesSwagger?

    public init(resourceId: Int64?, changes: PutCodeValuechangesSwagger?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

