//
// PutCachesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutCachesResponse: Codable {

    public var cacheType: PutCachechangesSwagger?

    public init(cacheType: PutCachechangesSwagger?) {
        self.cacheType = cacheType
    }


}

