//
// PutCentersCenterIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutCentersCenterIdRequest: Codable {

    public var name: String?

    public init(name: String?) {
        self.name = name
    }


}

