//
// PutDataTablesRequestChangeColumns.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutDataTablesRequestChangeColumns: Codable {

    public var name: String?
    public var newName: String?
    public var code: String?
    public var newCode: String?
    public var mandatory: Bool?

    public init(name: String?, newName: String?, code: String?, newCode: String?, mandatory: Bool?) {
        self.name = name
        self.newName = newName
        self.code = code
        self.newCode = newCode
        self.mandatory = mandatory
    }


}

