//
// PutDataTablesAppTableIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutDataTablesAppTableIdResponse: Codable {

    public var resourceId: Int64?
    public var changes: PutDataTablesAppTableIdResponseChanges?

    public init(resourceId: Int64?, changes: PutDataTablesAppTableIdResponseChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

