//
// PutDataTablesRequestAddColumns.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutDataTablesRequestAddColumns: Codable {

    public var name: String?
    public var type: String?
    public var code: String?
    public var mandatory: Bool?

    public init(name: String?, type: String?, code: String?, mandatory: Bool?) {
        self.name = name
        self.type = type
        self.code = code
        self.mandatory = mandatory
    }


}

