//
// PutFixedDepositAccountsAccountIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutFixedDepositAccountsAccountIdRequest: Codable {

    public var locale: String?
    public var depositAmount: Float?

    public init(locale: String?, depositAmount: Float?) {
        self.locale = locale
        self.depositAmount = depositAmount
    }


}

