//
// PutFixedDepositProductsProductIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutFixedDepositProductsProductIdResponse: Codable {

    public var resourceId: Int?
    public var changes: PutFixedDepositProductsChanges?

    public init(resourceId: Int?, changes: PutFixedDepositProductsChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

