//
// PutFinancialActivityAccountscommentsSwagger.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutFinancialActivityAccountscommentsSwagger: Codable {

    public var glAccountId: Int64?

    public init(glAccountId: Int64?) {
        self.glAccountId = glAccountId
    }


}

