//
// PutHookResponseChangesSwagger.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutHookResponseChangesSwagger: Codable {

    public var displayName: String?
    public var events: [Event]?
    public var config: [Field]?

    public init(displayName: String?, events: [Event]?, config: [Field]?) {
        self.displayName = displayName
        self.events = events
        self.config = config
    }


}

