//
// PutHolidaysHolidayIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutHolidaysHolidayIdResponse: Codable {

    public var resourceId: Int64?
    public var changes: PutHolidaysHolidayIdResponseChanges?

    public init(resourceId: Int64?, changes: PutHolidaysHolidayIdResponseChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

