//
// PutInterestRateChartsChartIdChartSlabsChartSlabIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutInterestRateChartsChartIdChartSlabsChartSlabIdResponse: Codable {

    public var resourceId: Int?
    public var changes: PutInterestRateChartsChartIdChartSlabsChartSlabIdRequest?

    public init(resourceId: Int?, changes: PutInterestRateChartsChartIdChartSlabsChartSlabIdRequest?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

