//
// PutNotesChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutNotesChanges: Codable {

    public var note: String?

    public init(note: String?) {
        self.note = note
    }


}

