//
// PutReportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutReportResponse: Codable {

    public var resourceId: Int64?
    public var changes: PutReportResponseChanges?

    public init(resourceId: Int64?, changes: PutReportResponseChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

