//
// PutResourceTypeResourceIdNotesNoteIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutResourceTypeResourceIdNotesNoteIdResponse: Codable {

    public var officeId: Int?
    public var clientId: Int?
    public var resourceId: Int?
    public var changes: PutNotesChanges?

    public init(officeId: Int?, clientId: Int?, resourceId: Int?, changes: PutNotesChanges?) {
        self.officeId = officeId
        self.clientId = clientId
        self.resourceId = resourceId
        self.changes = changes
    }


}

