//
// PutRolesRoleIdPermissionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutRolesRoleIdPermissionsRequest: Codable {

    public var permissions: PostRolesRoleIdPermissionsResponsePermissions?

    public init(permissions: PostRolesRoleIdPermissionsResponsePermissions?) {
        self.permissions = permissions
    }


}

