//
// PutRecurringDepositAccountsAccountIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutRecurringDepositAccountsAccountIdResponse: Codable {

    public var officeId: Int?
    public var clientId: Int?
    public var savingsId: Int?
    public var resourceId: Int?
    public var changes: PutRecurringDepositAccountsChanges?

    public init(officeId: Int?, clientId: Int?, savingsId: Int?, resourceId: Int?, changes: PutRecurringDepositAccountsChanges?) {
        self.officeId = officeId
        self.clientId = clientId
        self.savingsId = savingsId
        self.resourceId = resourceId
        self.changes = changes
    }


}

