//
// PutRolesRoleIdResponseChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutRolesRoleIdResponseChanges: Codable {

    public var _description: String?

    public init(_description: String?) {
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
    }


}

