//
// PutSelfUserResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSelfUserResponse: Codable {

    public var officeId: Int?
    public var resourceId: Int?
    public var changes: PutSelfUserChanges?

    public init(officeId: Int?, resourceId: Int?, changes: PutSelfUserChanges?) {
        self.officeId = officeId
        self.resourceId = resourceId
        self.changes = changes
    }


}

