//
// PutStandingInstructionsStandingInstructionIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutStandingInstructionsStandingInstructionIdRequest: Codable {

    public var recurrenceInterval: Int?

    public init(recurrenceInterval: Int?) {
        self.recurrenceInterval = recurrenceInterval
    }


}

