//
// PutStandingInstructionsStandingInstructionIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutStandingInstructionsStandingInstructionIdResponse: Codable {

    public var resourceId: Int?
    public var changes: PutUpdateStandingInstructionChanges?

    public init(resourceId: Int?, changes: PutUpdateStandingInstructionChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

