//
// PutSelfBeneficiariesTPTBeneficiaryIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSelfBeneficiariesTPTBeneficiaryIdResponse: Codable {

    public var resourceId: Int?
    public var changes: PutSelfBeneficiariesChanges?

    public init(resourceId: Int?, changes: PutSelfBeneficiariesChanges?) {
        self.resourceId = resourceId
        self.changes = changes
    }


}

