//
// PutSelfUserChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSelfUserChanges: Codable {

    public var passwordEncoded: String?

    public init(passwordEncoded: String?) {
        self.passwordEncoded = passwordEncoded
    }


}

