//
// PutSelfBeneficiariesTPTBeneficiaryIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSelfBeneficiariesTPTBeneficiaryIdRequest: Codable {

    public var name: String?
    public var transferLimit: Int?

    public init(name: String?, transferLimit: Int?) {
        self.name = name
        self.transferLimit = transferLimit
    }


}

