//
// PutSelfBeneficiariesChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSelfBeneficiariesChanges: Codable {

    public var transferLimit: Int?
    public var name: String?

    public init(transferLimit: Int?, name: String?) {
        self.transferLimit = transferLimit
        self.name = name
    }


}

