//
// PutTaxesGroupChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutTaxesGroupChanges: Codable {

    public var addComponents: [Int]?
    public var modifiedComponents: [PutTaxesGroupModifiedComponents]?
    public var name: String?

    public init(addComponents: [Int]?, modifiedComponents: [PutTaxesGroupModifiedComponents]?, name: String?) {
        self.addComponents = addComponents
        self.modifiedComponents = modifiedComponents
        self.name = name
    }


}

