//
// PutTellersTellerIdCashiersCashierIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutTellersTellerIdCashiersCashierIdResponse: Codable {

    public var resourceId: Int64?
    public var subResourceId: Int64?
    public var changes: PutTellersTellerIdCashiersCashierIdResponseChanges?

    public init(resourceId: Int64?, subResourceId: Int64?, changes: PutTellersTellerIdCashiersCashierIdResponseChanges?) {
        self.resourceId = resourceId
        self.subResourceId = subResourceId
        self.changes = changes
    }


}

