//
// PutTaxesGroupTaxGroupIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutTaxesGroupTaxGroupIdRequest: Codable {

    public var name: String?
    public var locale: String?
    public var taxComponents: [PutTaxesGroupTaxComponents]?
    public var dateFormat: String?

    public init(name: String?, locale: String?, taxComponents: [PutTaxesGroupTaxComponents]?, dateFormat: String?) {
        self.name = name
        self.locale = locale
        self.taxComponents = taxComponents
        self.dateFormat = dateFormat
    }


}

