//
// PutTaxesComponentsChanges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutTaxesComponentsChanges: Codable {

    public var percentage: Float?
    public var name: String?
    public var startDate: Date?

    public init(percentage: Float?, name: String?, startDate: Date?) {
        self.percentage = percentage
        self.name = name
        self.startDate = startDate
    }


}

