//
// PutTaxesComponentsTaxComponentIdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutTaxesComponentsTaxComponentIdRequest: Codable {

    public var name: String?
    public var percentage: Float?
    public var locale: String?
    public var dateFormat: String?
    public var startDate: String?

    public init(name: String?, percentage: Float?, locale: String?, dateFormat: String?, startDate: String?) {
        self.name = name
        self.percentage = percentage
        self.locale = locale
        self.dateFormat = dateFormat
        self.startDate = startDate
    }


}

