//
// QuestionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QuestionData: Codable {

    public var _id: Int64?
    public var responseDatas: [ResponseData]?
    public var componentKey: String?
    public var key: String?
    public var text: String?
    public var _description: String?
    public var sequenceNo: Int?

    public init(_id: Int64?, responseDatas: [ResponseData]?, componentKey: String?, key: String?, text: String?, _description: String?, sequenceNo: Int?) {
        self._id = _id
        self.responseDatas = responseDatas
        self.componentKey = componentKey
        self.key = key
        self.text = text
        self._description = _description
        self.sequenceNo = sequenceNo
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case responseDatas
        case componentKey
        case key
        case text
        case _description = "description"
        case sequenceNo
    }


}

