//
// ReportMailingJobRunHistoryData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportMailingJobRunHistoryData: Codable {

    public var _id: Int64?
    public var reportMailingJobId: Int64?
    public var startDateTime: Date?
    public var endDateTime: Date?
    public var status: String?
    public var errorMessage: String?
    public var errorLog: String?

    public init(_id: Int64?, reportMailingJobId: Int64?, startDateTime: Date?, endDateTime: Date?, status: String?, errorMessage: String?, errorLog: String?) {
        self._id = _id
        self.reportMailingJobId = reportMailingJobId
        self.startDateTime = startDateTime
        self.endDateTime = endDateTime
        self.status = status
        self.errorMessage = errorMessage
        self.errorLog = errorLog
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case reportMailingJobId
        case startDateTime
        case endDateTime
        case status
        case errorMessage
        case errorLog
    }


}

