//
// Role.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Role: Codable {

    public var _id: Int64?
    public var name: String?
    public var disabled: Bool?
    public var permissions: [Permission]?
    public var enabled: Bool?
    public var new: Bool?

    public init(_id: Int64?, name: String?, disabled: Bool?, permissions: [Permission]?, enabled: Bool?, new: Bool?) {
        self._id = _id
        self.name = name
        self.disabled = disabled
        self.permissions = permissions
        self.enabled = enabled
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case disabled
        case permissions
        case enabled
        case new
    }


}

