//
// Scorecard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Scorecard: Codable {

    public var _id: Int64?
    public var survey: Survey?
    public var question: Question?
    public var response: ModelResponse?
    public var appUser: AppUser?
    public var client: Client?
    public var createdOn: Date?
    public var value: Int?
    public var new: Bool?

    public init(_id: Int64?, survey: Survey?, question: Question?, response: ModelResponse?, appUser: AppUser?, client: Client?, createdOn: Date?, value: Int?, new: Bool?) {
        self._id = _id
        self.survey = survey
        self.question = question
        self.response = response
        self.appUser = appUser
        self.client = client
        self.createdOn = createdOn
        self.value = value
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case survey
        case question
        case response
        case appUser
        case client
        case createdOn
        case value
        case new
    }


}

