//
// TaxComponentHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaxComponentHistory: Codable {

    public var _id: Int64?
    public var createdBy: AppUser?
    public var createdDate: Date?
    public var lastModifiedBy: AppUser?
    public var lastModifiedDate: Date?
    public var percentage: Double?
    public var new: Bool?

    public init(_id: Int64?, createdBy: AppUser?, createdDate: Date?, lastModifiedBy: AppUser?, lastModifiedDate: Date?, percentage: Double?, new: Bool?) {
        self._id = _id
        self.createdBy = createdBy
        self.createdDate = createdDate
        self.lastModifiedBy = lastModifiedBy
        self.lastModifiedDate = lastModifiedDate
        self.percentage = percentage
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdBy
        case createdDate
        case lastModifiedBy
        case lastModifiedDate
        case percentage
        case new
    }


}

