//
// TaxGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaxGroup: Codable {

    public var _id: Int64?
    public var createdBy: AppUser?
    public var createdDate: Date?
    public var lastModifiedBy: AppUser?
    public var lastModifiedDate: Date?
    public var name: String?
    public var taxGroupMappings: [TaxGroupMappings]?
    public var new: Bool?

    public init(_id: Int64?, createdBy: AppUser?, createdDate: Date?, lastModifiedBy: AppUser?, lastModifiedDate: Date?, name: String?, taxGroupMappings: [TaxGroupMappings]?, new: Bool?) {
        self._id = _id
        self.createdBy = createdBy
        self.createdDate = createdDate
        self.lastModifiedBy = lastModifiedBy
        self.lastModifiedDate = lastModifiedDate
        self.name = name
        self.taxGroupMappings = taxGroupMappings
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdBy
        case createdDate
        case lastModifiedBy
        case lastModifiedDate
        case name
        case taxGroupMappings
        case new
    }


}

