//
// TemplateMapper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TemplateMapper: Codable {

    public var _id: Int64?
    public var mapperorder: Int?
    public var mapperkey: String?
    public var mappervalue: String?
    public var new: Bool?

    public init(_id: Int64?, mapperorder: Int?, mapperkey: String?, mappervalue: String?, new: Bool?) {
        self._id = _id
        self.mapperorder = mapperorder
        self.mapperkey = mapperkey
        self.mappervalue = mappervalue
        self.new = new
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case mapperorder
        case mapperkey
        case mappervalue
        case new
    }


}

